-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"833.45629882813" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-2506.8515625" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-221.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"881.96588134766" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-333.0432434082" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"201.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"581.21435546875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1443.5223388672" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"201.03123474121" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet