-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"942.27362060547" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-428.29135131836" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"8.0312538146973" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"685.88122558594" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"262.98254394531" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"8.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"70.873924255371" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"437.30694580078" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"8.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN