-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-1213.4315185547" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-1635.4008789063" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"8" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-2305.6186523438" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-479.21469116211" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-125.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-2487.7355957031" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1149.4748535156" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-125.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-987.36834716797" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"764.76422119141" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"8.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas