-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"11.349586486816" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"14.438842773438" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"64.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-1714.6519775391" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"263.85137939453" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"32.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"432.28814697266" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"143.67813110352" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"640.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"414.84188842773" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"765.193359375" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"96.031242370605" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet