-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-866.21063232422" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"351.01159667969" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"136.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-862.89129638672" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-920.31622314453" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"8.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-550.13391113281" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-28.123336791992" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"8.0000076293945" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet