-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-4561.3081054688" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"11360.37109375" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"183.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-6511.9370117188" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"11795.6484375" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"797.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-4395.2153320313" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"13164.28515625" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"797.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN