-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-963.20544433594" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-78.183540344238" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"388.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"171.18257141113" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-628.18212890625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"387.76824951172" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"0.63858032226563" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"413.82403564453" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"512.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-732.54241943359" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-670.57476806641" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"512.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas