-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"1069.7081298828" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"8.479793548584" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"16.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"21.916473388672" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1296.3316650391" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"160.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"568.55999755859" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-531.99322509766" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"160.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"1439.0010986328" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"1172.0106201172" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"152.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet