-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-1502.8762207031" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-55.089019775391" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"392.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-409.05380249023" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-570.23126220703" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"384.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1.8389654159546" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"226.75820922852" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"384.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-284.26324462891" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"525.17877197266" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"392.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1272.3702392578" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1167.8294677734" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"400.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas