-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-851.84033203125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"36.86067199707" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1501.2303466797" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-1204.8043212891" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-830.46307373047" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-1494.5244140625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"120.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-875.94116210938" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-203.36335754395" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"400.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1774.1953125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-264.20989990234" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-287.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas