-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"881.06475830078" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1251.9145507813" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"41.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"646.69342041016" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-552.78234863281" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"41.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"930.56475830078" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-938.21514892578" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"41.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"9" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN