-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-322.46865844727" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"3386.1193847656" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"87.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-680.0224609375" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1480.4055175781" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"74.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-873.27154541016" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1322.3981933594" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"74.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"878.31433105469" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-117.22863006592" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"74.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"2966.8054199219" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"435.2890625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"74.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"9" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1531.9688720703" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2550.5107421875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"74.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"11" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas