-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-233.28335571289" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-184.13133239746" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-51.219467163086" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-309.23785400391" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-718.07250976563" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"5.3246073722839" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN