-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-729.57073974609" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"224.03675842285" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"24.031242370605" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-540.65222167969" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1055.2940673828" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"24.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-118.42472076416" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-748.61895751953" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-255.96876525879" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-310.10778808594" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"188.05798339844" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-119.96875762939" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"905.34460449219" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"336.15170288086" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-383.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet