-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-1602.478515625" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1099.4611816406" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-740.90759277344" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-260.45184326172" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"368.75823974609" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-565.20385742188" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-31.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-1670.6779785156" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"537.96392822266" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet