-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-1161.4018554688" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-744.00372314453" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.031253814697266" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-136.78927612305" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"693.78253173828" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"38.859210968018" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"254.25392150879" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1148.5916748047" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-511.03775024414" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-652.16888427734" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-216.77685546875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"9" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1109.7218017578" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-243.57791137695" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"11" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas