-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-94.869583129883" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"532.50238037109" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"152.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-421.40618896484" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"441.55792236328" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-431.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet