-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"360.07284545898" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"461.814453125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"320.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-346.13232421875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1.1515312194824" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"448.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"110.97874450684" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-1130.1534423828" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"640.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-437.16235351563" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-207.68455505371" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"1280.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"10" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas