-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-8932.0458984375" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-389.2119140625" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"64.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-6466.1840820313" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-939.11938476563" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"72.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet