-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-4906.8305664063" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"5295.765625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"256.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-3888.3449707031" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1266.2041015625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"256.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-2340.8029785156" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2616.3527832031" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"256.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-574.96752929688" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2771.7331542969" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"256.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas