-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"8.2660675048828" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-1466.5166015625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-479.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-229.83755493164" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-1461.9008789063" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-223.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1178.3306884766" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-1031.2830810547" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1413.4532470703" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1283.1131591797" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-223.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-310.6005859375" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1218.4248046875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-159.88911437988" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-171.17144775391" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"741.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"8" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas