-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-40.423210144043" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-271.42892456055" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-63.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-488.81997680664" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"480.13391113281" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-63.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"175.66877746582" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1754.3801269531" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"32.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-445.86077880859" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1752.0065917969" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-111.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas