-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-450.20236206055" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1555.0936279297" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"186.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-1162.4599609375" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-288.39904785156" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"63.999992370605" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"30.45902633667" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1096.2418212891" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"64.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-1125.7087402344" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1948.9768066406" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"64.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet