-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-1329.8095703125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"956.72924804688" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1098.0063476563" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"978.24517822266" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"39.351226806641" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-348.541015625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"966.95251464844" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"10.158561706543" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"8" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas