-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"312.13430786133" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1045.4165039063" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"8.0312461853027" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-292.94882202148" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"838.38409423828" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-119.96875762939" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"832.37963867188" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"141.76013183594" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"264.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1223.1181640625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"180.00239562988" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"8.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas