-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"559.97204589844" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-55.80997467041" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"360.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-628.78088378906" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-641.19256591797" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"744.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"453.99145507813" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"58.769081115723" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"104.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"571.49041748047" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"186.93580627441" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"360.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas