-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-193.29638671875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"487.9655456543" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-193.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-1419.4830322266" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"1125.7657470703" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"4.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"52.35205078125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"437.79479980469" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"8.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN