-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"721.41125488281" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"54.074844360352" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"414.04791259766" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-645.51135253906" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"864.56872558594" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"703.05053710938" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"8.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-188.17582702637" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"228.84759521484" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"8" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas