-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-4526.1796875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-4007.876953125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"384.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-4890.0151367188" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-5055.9721679688" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"512.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-4818.3325195313" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-4304.0717773438" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"256.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-3429.8896484375" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-5326.1552734375" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"64.031265258789" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet