-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-237.59956359863" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"690.90081787109" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"109.46624755859" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"624.12182617188" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2003.8240966797" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"72.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-227.06802368164" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2339.0498046875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"64.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"163.54685974121" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-141.83306884766" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"72.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1946.9166259766" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1070.0744628906" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-62.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas