-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-3155.8264160156" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"395.65832519531" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-296.283203125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-2223.8334960938" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"573.61700439453" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-298.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-1603.0994873047" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"989.50427246094" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-108.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet