-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-246.87316894531" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"1742.2725830078" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"40.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-575.71478271484" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"1340.6162109375" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-87.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-651.16070556641" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"1486.1005859375" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"168.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet