-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-190.87916564941" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-377.99722290039" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"323.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"311.71130371094" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"232.12812805176" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"321.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-110.48857116699" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"17.301645278931" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"65.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"353.94116210938" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-86.678939819336" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"65.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet