-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-666.29522705078" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"972.00994873047" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-127.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"695.4765625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1185.5861816406" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-127.96876525879" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"219.20042419434" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"528.21893310547" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.031280517578125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"267.07485961914" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-235.87437438965" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-824.66094970703" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-458.70571899414" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-875.31848144531" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-451.35556030273" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-246.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"163.81379699707" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-694.73620605469" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-117.96874237061" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-272.72155761719" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-66.759376525879" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.031242370605469" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"8" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas