-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"693.79260253906" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1373.6278076172" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"272.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"543.09600830078" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1740.4909667969" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"230.61885070801" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"23.102947235107" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"272.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-572.72454833984" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-860.69909667969" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN