-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-982.22528076172" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"0.85103511810303" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"432.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-2012.9270019531" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"402.42575073242" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"432.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-1064.9145507813" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"182.08981323242" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"256.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-2011.6711425781" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-24.186096191406" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-975.40740966797" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-549.26110839844" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"136.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-978.78894042969" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-450.75277709961" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"256.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet