-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-359.96215820313" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-102.79405975342" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"33.820320129395" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"265.32113647461" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-349.41302490234" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"266.66647338867" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"144.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-106.68253326416" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"563.72790527344" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-180.83471679688" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1019.9105224609" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN