-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-69.050537109375" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"485.13519287109" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"256.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-257.94686889648" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"749.986328125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"64.031257629395" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-353.67413330078" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"1136.4318847656" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"320.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet