-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-410.98101806641" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-402.20751953125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"478.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-933.31878662109" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-457.15579223633" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"478.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-697.97015380859" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"619.44891357422" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"560.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-642.43414306641" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-378.67443847656" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-684.04644775391" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1191.5301513672" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"4.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-648.57934570313" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1122.7854003906" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"192.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-319.28594970703" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-267.81091308594" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"192.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"8" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1012.4498291016" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-269.36026000977" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"192.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"9" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas