-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"506.22314453125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"153.5484161377" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-33.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"42.899463653564" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"518.77667236328" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-33.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"258.02383422852" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"12.750198364258" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"93.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"310.74728393555" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-923.47637939453" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-47.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN