-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"673.04150390625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"986.73913574219" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1044.9913330078" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-850.71447753906" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"3061.2075195313" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-533.51348876953" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"2104.4013671875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1879.7625732422" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"9" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"3048.4748535156" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1990.5754394531" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"10.085445404053" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"11" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas