-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"1169.8225097656" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-336.283203125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-7.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1223.6539306641" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-583.43524169922" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-7.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1429.0993652344" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-338.89889526367" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-134.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1339.6075439453" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"346.44616699219" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1483.0469970703" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-146.20341491699" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-7.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas