-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-80.777755737305" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-61.868286132813" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"83.304061889648" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-49.293323516846" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"745.93927001953" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"350.87124633789" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"150.56394958496" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-224.83966064453" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"532.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN