-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-1029.0777587891" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"542.17645263672" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"136.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-700.15716552734" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"881.87365722656" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-826.17028808594" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"626.365234375" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"408.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-1026.4011230469" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"878.05493164063" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"272.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet