-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"906.54083251953" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"190.84750366211" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-7.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"1550.7097167969" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-334.98355102539" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-134.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"943.09155273438" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"335.30401611328" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"256.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"911.00982666016" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"222.66677856445" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet