-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-895.62298583984" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1204.3663330078" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-251.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-62.297378540039" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-154.79797363281" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"8.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-817.23992919922" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-990.92742919922" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-1567.4180908203" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1288.5515136719" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"264.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-1696.0150146484" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1227.2468261719" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-251.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-1289.5892333984" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1506.3973388672" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"8" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"955.20965576172" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"612.53070068359" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"400.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"9" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN