-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"571.06420898438" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-2055.1311035156" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-255.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"1877.9149169922" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-2146.98828125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"644.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"108.99507141113" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1214.2912597656" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"454.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"1031.7119140625" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-2735.0065917969" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"454.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"1324.9091796875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-415.27679443359" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"300.41366577148" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"1071.3579101563" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-85.362106323242" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"64" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet