-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"276.08563232422" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-528.59057617188" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"45.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-480.30233764648" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"597.35803222656" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"130.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-936.12567138672" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"2122.1169433594" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"232.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"608.83874511719" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"2137.5698242188" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"80.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN