-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"541.24505615234" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-62.537307739258" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"208.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-37.522674560547" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"77.300437927246" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"178.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-774.37976074219" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"57.207149505615" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"16.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"8" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"288.56716918945" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"515.66162109375" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"16.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"11" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas