-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"898.42169189453" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1028.5989990234" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-483.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-401.12548828125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-364.90570068359" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-507.19189453125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"123.82884979248" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2814.4814453125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-794.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1168.7736816406" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2488.8471679688" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-512" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas