-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-489.38507080078" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"645.90759277344" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"208.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-175.06819152832" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"849.61999511719" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"208.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"151.05026245117" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"684.12359619141" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"343.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN