-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-98.636245727539" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-42.744323730469" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-147.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"184.9541015625" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"919.50842285156" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"188.86358642578" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-123.79414367676" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"71.699371337891" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-182.98774719238" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"166.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-575.45825195313" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"1457.0600585938" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-147.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-481.94781494141" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1661.1268310547" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-7.9687461853027" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"8" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN