-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"197.67953491211" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"728.91253662109" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"72.031257629395" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"779.58929443359" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-2.3315019607544" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"32.031242370605" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"907.98901367188" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-986.85321044922" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"176.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN