-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"122.65041351318" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"147.02972412109" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-88.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"706.51617431641" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"533.18609619141" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"47.031253814697" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"458.6120300293" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"51.719722747803" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"47.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN