-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-2427.0532226563" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-482.41253662109" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"8.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"473.00393676758" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1370.361328125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-15.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-1076.0612792969" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"1123.3760986328" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-799.86010742188" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"584.05120849609" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"136.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-2497.8811035156" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"1045.8388671875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"8.0312576293945" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-3771.4985351563" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-90.527038574219" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"8.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-3628.8264160156" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1090.1252441406" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"8.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet