-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"415.20825195313" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1060.7275390625" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-159.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"697.28454589844" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-2590.9697265625" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-31.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"908.88256835938" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-2585.8950195313" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"304.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-392.64715576172" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-2355.0998535156" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-223.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"1768.3861083984" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-931.27856445313" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-31.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-825.49853515625" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-792.73791503906" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"192.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet