-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-207.64529418945" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"70.430847167969" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-135.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"367.64077758789" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-873.08929443359" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"96.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-653.13958740234" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1040.1364746094" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"224.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-228.88485717773" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-2538.3093261719" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"232.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN