-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"734.12634277344" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-175.19111633301" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"144.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"736.61737060547" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-135.93933105469" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN