-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"1364.6887207031" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-2356.8361816406" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-1383.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"382.07400512695" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-2043.7927246094" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-1279.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"1503.126953125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1232.8909912109" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-1279.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"226.82766723633" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1745.6763916016" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-1383.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN