-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"232.05508422852" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"43.859951019287" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"64.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"151.30415344238" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-674.01983642578" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"440.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-1127.6323242188" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"1239.9538574219" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"440.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-312.74313354492" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"1704.3006591797" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"680.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-450.57046508789" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"612.10076904297" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"676.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-208.70202636719" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-608.90380859375" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"680.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"8" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"296.9196472168" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-578.64135742188" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"1128.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"9" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet