-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"106.73938751221" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"325.32388305664" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"288.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"494.91363525391" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-5.5627684593201" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"144.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"1004.5123901367" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-371.14138793945" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-27.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN