-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-990.71789550781" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-31.554229736328" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-1023.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-790.3017578125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-122.45938110352" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-895.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1092.9473876953" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"375.75445556641" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-767.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1318.9720458984" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"308.06085205078" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-895.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"9" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas