-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"281.45666503906" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-22.010936737061" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"144.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-414.14410400391" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-944.86749267578" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"8.0312538146973" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN