-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-672.23077392578" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-1048.6263427734" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"80.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-54.79076385498" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"503.32373046875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"200.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-265.28695678711" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-854.89916992188" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"336.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-965.310546875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-820.10949707031" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"64.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas