-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-615.31921386719" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-991.72723388672" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-127.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-228.46446228027" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-567.27679443359" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-1816.8862304688" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1523.5965576172" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-1237.955078125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1635.1608886719" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"8" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-646.85955810547" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1570.2314453125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-127.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"9" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-309.83203125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-1115.4459228516" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-123.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"10" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-54.403751373291" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-550.48345947266" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"11" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN