-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-73.104949951172" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"2215.7143554688" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-355.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-8.036919593811" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"187.55557250977" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-353.44314575195" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"576.46215820313" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-923.63812255859" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-187.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-572.08044433594" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-438.37805175781" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"248.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN