-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"237.11225891113" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-828.89385986328" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-344.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-303.38040161133" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-990.28314208984" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-102.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-24.955762863159" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-750.78466796875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"35.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet