-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-869.28717041016" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"1004.8582763672" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"8.0312538146973" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-673.39801025391" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-271.11538696289" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"8.0312538146973" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-740.04040527344" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"398.62899780273" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"224.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-1942.0885009766" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"143.3936920166" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"224.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN