-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"447.78524780273" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-585.78393554688" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"188.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"29.437755584717" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-422.11663818359" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"188.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN