-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"426.83303833008" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-828.74591064453" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"188.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"104.9801940918" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-429.99426269531" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"188.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN