-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"1370.4827880859" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"214.59320068359" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-127.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-465.81231689453" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"200.52128601074" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-127.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"1338.4158935547" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"25.906188964844" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"384.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-442.3332824707" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"350.67462158203" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"384.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-439.87503051758" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"30.419555664063" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"1331.8177490234" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"355.46041870117" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet