-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-2001.7401123047" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1007.0629272461" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"257.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-338.33251953125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-865.84594726563" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"260.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-2431.8740234375" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1215.7147216797" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"392.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet