-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"1340.4595947266" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"1454.9151611328" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-331.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"1859.2669677734" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"1792.4967041016" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-567.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN