-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-91.461647033691" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"903.13690185547" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"128.03126525879" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"348.74481201172" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"260.94839477539" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-947.44165039063" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"776.90686035156" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"656.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-596.81707763672" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"491.26470947266" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"268.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN