-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"557.93865966797" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-785.86120605469" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"272.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-150.13159179688" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"425.19451904297" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"272.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"315.30517578125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"258.25457763672" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-175.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-9.9386405944824" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1468.8571777344" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-175.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"1015.5952758789" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"1524.2720947266" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"64.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-164.55117797852" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-381.23944091797" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"448.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"9" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet