-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"8357.1904296875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"7181.0932617188" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"5760.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"8755.8779296875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"5751.7114257813" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"5760.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"9060.4326171875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"7095.4438476563" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"5920.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN