-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-1311.4973144531" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"3691.9685058594" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-479.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-44.933807373047" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2534.1181640625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-495.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"328.41693115234" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2767.7917480469" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-415.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-854.01940917969" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1955.5169677734" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-223.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-2165.6823730469" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2043.5732421875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-223.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-150.98533630371" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"816.90814208984" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"32.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas