-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-820.74865722656" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-1482.3283691406" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"428.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1631.451171875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"208.48773193359" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"305.1653137207" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1526.8266601563" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-287.89144897461" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"302.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1830.4399414063" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1264.3894042969" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"172.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas