-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-1908.1265869141" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-117.42778778076" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-733.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-861.98718261719" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"851.18743896484" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-998.91455078125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-479.87298583984" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"712.98645019531" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-1263.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN