-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"41.513084411621" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"425.51815795898" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"432.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"768.20373535156" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"550.68292236328" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"288.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"206.14320373535" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-152.66217041016" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN