-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"846.54644775391" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1191.0600585938" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"640.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"761.50207519531" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-694.43377685547" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"640.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-187.67813110352" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1503.3837890625" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"436.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"797.2294921875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1316.7985839844" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"436.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"87.607856750488" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1089.1212158203" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"544.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"8" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet