-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"53.9453125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"287.13064575195" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"168.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-138.22348022461" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"46.585983276367" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"48.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-126.54253387451" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"545.53045654297" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-195.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN