-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"999.48236083984" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"804.34741210938" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"24.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"2543.8527832031" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-672.619140625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"13.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1631.8179931641" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-1506.2969970703" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"94.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"709.02294921875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-2009.5692138672" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-242.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1981.4133300781" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1488.5217285156" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"106.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas