-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-128.75958251953" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"20.908172607422" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-81.770011901855" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"1345.5014648438" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-159.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-1105.1840820313" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"1089.5452880859" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-127.96874237061" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-301.14678955078" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"146.77348327637" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"0.031246185302734" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-62.049140930176" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1317.4219970703" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet