-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-779.4140625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"807.36474609375" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"257.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-135.37333679199" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-458.27899169922" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1213.1414794922" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"113.86022949219" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"136.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-120.17094421387" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"694.71783447266" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas