-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-1812.5581054688" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-1391.4141845703" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-379.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1598.4040527344" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-668.63623046875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-215.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-3139.2709960938" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-391.92727661133" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-635.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas

