-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-134.63372802734" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"75.231239318848" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"160.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"394.43063354492" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-318.1357421875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"32.031246185303" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"1055.7747802734" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-938.40197753906" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"0.0018386840820313" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet