-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-23.032493591309" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"1146.6594238281" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"88.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"1262.1018066406" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"1064.5526123047" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"88.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN