-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"1260.5234375" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-310.63903808594" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"371.21475219727" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-78.88801574707" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"168.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"1017.2865600586" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"-233.39636230469" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-63.968746185303" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN