-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"370.16912841797" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-273.07476806641" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"384.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"8" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas