-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-276.36346435547" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"102.9451675415" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-180.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-1299.28515625" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"547.18975830078" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-1130.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"-930.18756103516" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-253.7074432373" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-886.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet