-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-1584.5875244141" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1322.6198730469" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-7.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-2059.2890625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2890.5100097656" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-103.96875762939" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-2527.3598632813" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2628.716796875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"48.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-2375.9301757813" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"688.25354003906" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1137.6300048828" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1660.3208007813" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-7.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas