-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"1509.5063476563" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2018.0319824219" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"160.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"435.67202758789" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2389.8435058594" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"496.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1322.3110351563" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"118.55281066895" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"16.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1792.6597900391" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1725.5460205078" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-159.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1008.0467529297" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1096.6647949219" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-703.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"8" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"1128.2469482422" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1650.1302490234" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-159.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"10" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas