-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"923.99865722656" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"1412.0269775391" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"160.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"951.38745117188" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"1922.8244628906" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"-159.96875" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"1975.6569824219" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"945.99645996094" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"868.97717285156" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"2048.6713867188" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"160.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"1418.5649414063" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"403.27401733398" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"16.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by NECROSSIN