-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"459.11157226563" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-86.382202148438" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-639.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"397.33096313477" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"207.25921630859" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-495.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"510.92663574219" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"624.50378417969" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"-639.96875" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet