-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-806.1640625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2275.0297851563" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-15.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1190.1237792969" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2899.5869140625" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-14.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-2111.8564453125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"677.27081298828" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"128.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-3292.9233398438" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"1988.4754638672" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"64.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"7" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-1250.0122070313" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"2320.1630859375" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-11.968753814697" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"8" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas