-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-438.26867675781" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"50.427501678467" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.031253814697266" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-79.995803833008" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-560.90405273438" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"-159.96875" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"147.75582885742" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-1115.9455566406" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"160.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"-78.22745513916" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-573.68243408203" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"0.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"6" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas