-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"692.86157226563" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-34.981292724609" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"64.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"845.7958984375" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"485.71917724609" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"64.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"true" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"875.07232666016" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-626.31024169922" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"64.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Y,"639.88220214844" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.X,"-587.27215576172" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Z,"176.03125" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by Deluvas
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Deluvas