-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"136.30987548828" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-1311.5609130859" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"76.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet