-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"-692.25909423828" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"901.18963623047" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"80.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-783.94561767578" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"452.79776000977" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"320.03125" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"4" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Y,"-1485.0368652344" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.X,"1069.25" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Z,"0" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.ID,"5" ) -- inserted by NECROSSIN
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by NECROSSIN