-- File generated by the Mr. Green ZS Ammo Box saver
-- www.left4green.com - www.mr-green.nl
 print ("-++++++ Loaded Ammo Box Spawn Points for this map  -+++++++")

table.insert( AmmoDropPoints.Y,"2302.9506835938" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"157.31460571289" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"313.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"1" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"1337.1567382813" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"-23.46573638916" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"64.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"2" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Y,"735.14050292969" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.X,"1369.2145996094" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Z,"64.03125" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.ID,"3" ) -- inserted by Pufulet
table.insert( AmmoDropPoints.Switch,"false" ) -- inserted by Pufulet