-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"-999.76287841797") -- PosX
table.insert(DropPointsY,"916.90130615234") -- PosY
table.insert(DropPointsZ,"-29.11806678772") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-894.72161865234") -- PosX
table.insert(DropPointsY,"644.98962402344") -- PosY
table.insert(DropPointsZ,"-83.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1245.0330810547") -- PosX
table.insert(DropPointsY,"941.01715087891") -- PosY
table.insert(DropPointsZ,"41.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1261.4349365234") -- PosX
table.insert(DropPointsY,"658.43957519531") -- PosY
table.insert(DropPointsZ,"41.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-519.53100585938") -- PosX
table.insert(DropPointsY,"877.7099609375") -- PosY
table.insert(DropPointsZ,"41.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-717.08587646484") -- PosX
table.insert(DropPointsY,"925.14739990234") -- PosY
table.insert(DropPointsZ,"41.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1003.9991455078") -- PosX
table.insert(DropPointsY,"632.63714599609") -- PosY
table.insert(DropPointsZ,"232.6237487793") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-783.04089355469") -- PosX
table.insert(DropPointsY,"752.19750976563") -- PosY
table.insert(DropPointsZ,"224.6237487793") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1002.5697631836") -- PosX
table.insert(DropPointsY,"890.79351806641") -- PosY
table.insert(DropPointsZ,"169.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-986.43798828125") -- PosX
table.insert(DropPointsY,"1051.3364257813") -- PosY
table.insert(DropPointsZ,"231.1237487793") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-820.46423339844") -- PosX
table.insert(DropPointsY,"642.79968261719") -- PosY
table.insert(DropPointsZ,"298.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-934.65423583984") -- PosX
table.insert(DropPointsY,"1076.7045898438") -- PosY
table.insert(DropPointsZ,"298.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-539.53381347656") -- PosX
table.insert(DropPointsY,"644.63696289063") -- PosY
table.insert(DropPointsZ,"41.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-996.58288574219") -- PosX
table.insert(DropPointsY,"627.93170166016") -- PosY
table.insert(DropPointsZ,"41.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-27.931930541992") -- PosX
table.insert(DropPointsY,"-168.09320068359") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-2035.6066894531") -- PosX
table.insert(DropPointsY,"-156.39619445801") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1449.8533935547") -- PosX
table.insert(DropPointsY,"924.17596435547") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1432.5423583984") -- PosX
table.insert(DropPointsY,"7.1832356452942") -- PosY
table.insert(DropPointsZ,"93.956260681152") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1847.5086669922") -- PosX
table.insert(DropPointsY,"-10.139751434326") -- PosY
table.insert(DropPointsZ,"122.39196777344") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1642.7637939453") -- PosX
table.insert(DropPointsY,"250.24821472168") -- PosY
table.insert(DropPointsZ,"-110.9780960083") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1854.7502441406") -- PosX
table.insert(DropPointsY,"-19.055223464966") -- PosY
table.insert(DropPointsZ,"-176.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1162.8355712891") -- PosX
table.insert(DropPointsY,"798.85949707031") -- PosY
table.insert(DropPointsZ,"286.96340942383") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1152.6563720703") -- PosX
table.insert(DropPointsY,"1017.7540283203") -- PosY
table.insert(DropPointsZ,"40.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-536.34350585938") -- PosX
table.insert(DropPointsY,"1012.2220458984") -- PosY
table.insert(DropPointsZ,"110.37295532227") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-913.18536376953") -- PosX
table.insert(DropPointsY,"-147.16172790527") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ