-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"-4716.3325195313") -- PosX
table.insert(DropPointsY,"4116.7890625") -- PosY
table.insert(DropPointsZ,"547.3408203125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4702.2329101563") -- PosX
table.insert(DropPointsY,"4097.158203125") -- PosY
table.insert(DropPointsZ,"394.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4848.4765625") -- PosX
table.insert(DropPointsY,"3698.7329101563") -- PosY
table.insert(DropPointsZ,"394.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4655.4111328125") -- PosX
table.insert(DropPointsY,"3586.9211425781") -- PosY
table.insert(DropPointsZ,"394.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-3948.171875") -- PosX
table.insert(DropPointsY,"3825.8286132813") -- PosY
table.insert(DropPointsZ,"207.84475708008") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-3792.5446777344") -- PosX
table.insert(DropPointsY,"3264.01953125") -- PosY
table.insert(DropPointsZ,"68.794975280762") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4631.0556640625") -- PosX
table.insert(DropPointsY,"3571.5395507813") -- PosY
table.insert(DropPointsZ,"265.12124633789") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4451.169921875") -- PosX
table.insert(DropPointsY,"3925.0495605469") -- PosY
table.insert(DropPointsZ,"309.84375") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4656.9267578125") -- PosX
table.insert(DropPointsY,"3867.7150878906") -- PosY
table.insert(DropPointsZ,"241.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4853.5541992188") -- PosX
table.insert(DropPointsY,"4126.673828125") -- PosY
table.insert(DropPointsZ,"241.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4560.1000976563") -- PosX
table.insert(DropPointsY,"4154.05859375") -- PosY
table.insert(DropPointsZ,"306.10452270508") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4527.958984375") -- PosX
table.insert(DropPointsY,"4015.6499023438") -- PosY
table.insert(DropPointsZ,"303.14614868164") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4440.5810546875") -- PosX
table.insert(DropPointsY,"4123.998046875") -- PosY
table.insert(DropPointsZ,"460.26373291016") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-5667.3720703125") -- PosX
table.insert(DropPointsY,"3532.4133300781") -- PosY
table.insert(DropPointsZ,"67.314254760742") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-5573.7133789063") -- PosX
table.insert(DropPointsY,"3930.7202148438") -- PosY
table.insert(DropPointsZ,"122.36038970947") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-3944.0473632813") -- PosX
table.insert(DropPointsY,"4183.5854492188") -- PosY
table.insert(DropPointsZ,"125.34499359131") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-5763.9604492188") -- PosX
table.insert(DropPointsY,"4183.0805664063") -- PosY
table.insert(DropPointsZ,"53.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-5890.9130859375") -- PosX
table.insert(DropPointsY,"3928.6789550781") -- PosY
table.insert(DropPointsZ,"210.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-5982.5366210938") -- PosX
table.insert(DropPointsY,"4116.6274414063") -- PosY
table.insert(DropPointsZ,"53.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-5555.9130859375") -- PosX
table.insert(DropPointsY,"3634.1801757813") -- PosY
table.insert(DropPointsZ,"-129.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-5289.3940429688") -- PosX
table.insert(DropPointsY,"3608.2785644531") -- PosY
table.insert(DropPointsZ,"-129.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-3816.1740722656") -- PosX
table.insert(DropPointsY,"3614.826171875") -- PosY
table.insert(DropPointsZ,"-129.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-3591.0009765625") -- PosX
table.insert(DropPointsY,"4203.96875") -- PosY
table.insert(DropPointsZ,"-129.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-3922.5327148438") -- PosX
table.insert(DropPointsY,"3902.2902832031") -- PosY
table.insert(DropPointsZ,"-66.765815734863") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-3859.8664550781") -- PosX
table.insert(DropPointsY,"4123.8041992188") -- PosY
table.insert(DropPointsZ,"-129.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4365.7822265625") -- PosX
table.insert(DropPointsY,"4111.396484375") -- PosY
table.insert(DropPointsZ,"-260.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4687.17578125") -- PosX
table.insert(DropPointsY,"4138.6826171875") -- PosY
table.insert(DropPointsZ,"-499.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4546.3247070313") -- PosX
table.insert(DropPointsY,"4324.7514648438") -- PosY
table.insert(DropPointsZ,"-387.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4472.3017578125") -- PosX
table.insert(DropPointsY,"4114.2275390625") -- PosY
table.insert(DropPointsZ,"-119.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-4947.2104492188") -- PosX
table.insert(DropPointsY,"4123.0141601563") -- PosY
table.insert(DropPointsZ,"-136.46875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-5752.40234375") -- PosX
table.insert(DropPointsY,"4259.6713867188") -- PosY
table.insert(DropPointsZ,"-260.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-5161.3315429688") -- PosX
table.insert(DropPointsY,"4134.2978515625") -- PosY
table.insert(DropPointsZ,"-417.634765625") -- PosZ