-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Ywa
table.insert(DropPointsX,"-644.81378173828") -- PosX
table.insert(DropPointsY,"-140.76733398438") -- PosY
table.insert(DropPointsZ,"74.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-70.804306030273") -- PosX
table.insert(DropPointsY,"905.52429199219") -- PosY
table.insert(DropPointsZ,"74.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-214.15573120117") -- PosX
table.insert(DropPointsY,"-116.01894378662") -- PosY
table.insert(DropPointsZ,"112.72049713135") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-517.45520019531") -- PosX
table.insert(DropPointsY,"677.58258056641") -- PosY
table.insert(DropPointsZ,"74.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-104.12037658691") -- PosX
table.insert(DropPointsY,"1787.0872802734") -- PosY
table.insert(DropPointsZ,"74.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"509.06954956055") -- PosX
table.insert(DropPointsY,"1610.1677246094") -- PosY
table.insert(DropPointsZ,"186.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"383.18450927734") -- PosX
table.insert(DropPointsY,"1906.1286621094") -- PosY
table.insert(DropPointsZ,"138.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"567.42138671875") -- PosX
table.insert(DropPointsY,"2210.7229003906") -- PosY
table.insert(DropPointsZ,"138.00276184082") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"377.88735961914") -- PosX
table.insert(DropPointsY,"2575.5803222656") -- PosY
table.insert(DropPointsZ,"138.47160339355") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"363.68493652344") -- PosX
table.insert(DropPointsY,"3004.3286132813") -- PosY
table.insert(DropPointsZ,"74.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1044.96875") -- PosX
table.insert(DropPointsY,"2750.9641113281") -- PosY
table.insert(DropPointsZ,"74.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1248.2623291016") -- PosX
table.insert(DropPointsY,"2651.8994140625") -- PosY
table.insert(DropPointsZ,"74.044708251953") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1528.4670410156") -- PosX
table.insert(DropPointsY,"2779.8994140625") -- PosY
table.insert(DropPointsZ,"74.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2106.1811523438") -- PosX
table.insert(DropPointsY,"2982.44140625") -- PosY
table.insert(DropPointsZ,"74.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1783.8041992188") -- PosX
table.insert(DropPointsY,"1983.5777587891") -- PosY
table.insert(DropPointsZ,"74.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1702.93359375") -- PosX
table.insert(DropPointsY,"1456.951171875") -- PosY
table.insert(DropPointsZ,"74.032501220703") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1475.3360595703") -- PosX
table.insert(DropPointsY,"1055.6395263672") -- PosY
table.insert(DropPointsZ,"80.811080932617") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2318.2314453125") -- PosX
table.insert(DropPointsY,"969.48040771484") -- PosY
table.insert(DropPointsZ,"119.57904052734") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2791.3955078125") -- PosX
table.insert(DropPointsY,"1374.9991455078") -- PosY
table.insert(DropPointsZ,"74.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2616.96875") -- PosX
table.insert(DropPointsY,"1554.96875") -- PosY
table.insert(DropPointsZ,"74.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2165.1396484375") -- PosX
table.insert(DropPointsY,"729.10736083984") -- PosY
table.insert(DropPointsZ,"87.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2062.98828125") -- PosX
table.insert(DropPointsY,"313.36627197266") -- PosY
table.insert(DropPointsZ,"98.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2187.1967773438") -- PosX
table.insert(DropPointsY,"6.3894195556641") -- PosY
table.insert(DropPointsZ,"141.01223754883") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2068.8732910156") -- PosX
table.insert(DropPointsY,"-74.03125") -- PosY
table.insert(DropPointsZ,"87.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2784.4936523438") -- PosX
table.insert(DropPointsY,"-144.52262878418") -- PosY
table.insert(DropPointsZ,"87.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2479.9541015625") -- PosX
table.insert(DropPointsY,"318.75982666016") -- PosY
table.insert(DropPointsZ,"87.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3471.4489746094") -- PosX
table.insert(DropPointsY,"676.05358886719") -- PosY
table.insert(DropPointsZ,"87.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3551.4460449219") -- PosX
table.insert(DropPointsY,"-101.28218078613") -- PosY
table.insert(DropPointsZ,"87.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3547.2924804688") -- PosX
table.insert(DropPointsY,"-331.54742431641") -- PosY
table.insert(DropPointsZ,"87.499443054199") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3351.4057617188") -- PosX
table.insert(DropPointsY,"-9.9658889770508") -- PosY
table.insert(DropPointsZ,"87.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1467.5815429688") -- PosX
table.insert(DropPointsY,"-663.76220703125") -- PosY
table.insert(DropPointsZ,"74.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-33.817474365234") -- PosX
table.insert(DropPointsY,"-861.97119140625") -- PosY
table.insert(DropPointsZ,"96.835151672363") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-481.79382324219") -- PosX
table.insert(DropPointsY,"-657.00189208984") -- PosY
table.insert(DropPointsZ,"86.772308349609") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"434.31399536133") -- PosX
table.insert(DropPointsY,"-1203.6949462891") -- PosY
table.insert(DropPointsZ,"94.442611694336") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"571.68103027344") -- PosX
table.insert(DropPointsY,"-880.53057861328") -- PosY
table.insert(DropPointsZ,"137.94454956055") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1049.2443847656") -- PosX
table.insert(DropPointsY,"-1078.1480712891") -- PosY
table.insert(DropPointsZ,"122.03121185303") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1341.8802490234") -- PosX
table.insert(DropPointsY,"-700.00909423828") -- PosY
table.insert(DropPointsZ,"74.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"845.81311035156") -- PosX
table.insert(DropPointsY,"496.85592651367") -- PosY
table.insert(DropPointsZ,"144.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1112.8958740234") -- PosX
table.insert(DropPointsY,"717.98187255859") -- PosY
table.insert(DropPointsZ,"111.8405380249") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"574.71936035156") -- PosX
table.insert(DropPointsY,"1281.2613525391") -- PosY
table.insert(DropPointsZ,"74.03125") -- PosZ