-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"-183.97496032715") -- PosX
table.insert(DropPointsY,"-284.05172729492") -- PosY
table.insert(DropPointsZ,"104.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-168.83976745605") -- PosX
table.insert(DropPointsY,"-445.22537231445") -- PosY
table.insert(DropPointsZ,"104.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"444.74243164063") -- PosX
table.insert(DropPointsY,"-720.67352294922") -- PosY
table.insert(DropPointsZ,"360.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"405.03125") -- PosX
table.insert(DropPointsY,"-76.54736328125") -- PosY
table.insert(DropPointsZ,"364.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"405.03125") -- PosX
table.insert(DropPointsY,"-76.54736328125") -- PosY
table.insert(DropPointsZ,"364.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"446.33807373047") -- PosX
table.insert(DropPointsY,"42.637474060059") -- PosY
table.insert(DropPointsZ,"360.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"615.96875") -- PosX
table.insert(DropPointsY,"24.03125") -- PosY
table.insert(DropPointsZ,"360.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"609.05053710938") -- PosX
table.insert(DropPointsY,"567.80834960938") -- PosY
table.insert(DropPointsZ,"277.53369140625") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"537.40905761719") -- PosX
table.insert(DropPointsY,"737.01538085938") -- PosY
table.insert(DropPointsZ,"277.94125366211") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"190.77687072754") -- PosX
table.insert(DropPointsY,"659.34661865234") -- PosY
table.insert(DropPointsZ,"360.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"153.06269836426") -- PosX
table.insert(DropPointsY,"536.03125") -- PosY
table.insert(DropPointsZ,"360.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"221.07197570801") -- PosX
table.insert(DropPointsY,"928.79217529297") -- PosY
table.insert(DropPointsZ,"405.64303588867") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"283.3620300293") -- PosX
table.insert(DropPointsY,"420.29382324219") -- PosY
table.insert(DropPointsZ,"360.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"476.49496459961") -- PosX
table.insert(DropPointsY,"546.02325439453") -- PosY
table.insert(DropPointsZ,"232.49980163574") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"137.7421875") -- PosX
table.insert(DropPointsY,"544.69226074219") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"57.76403427124") -- PosX
table.insert(DropPointsY,"550.63818359375") -- PosY
table.insert(DropPointsZ,"224.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"335.21099853516") -- PosX
table.insert(DropPointsY,"574.57861328125") -- PosY
table.insert(DropPointsZ,"-23.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"40.123638153076") -- PosX
table.insert(DropPointsY,"718.95874023438") -- PosY
table.insert(DropPointsZ,"-23.968748092651") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"476.25604248047") -- PosX
table.insert(DropPointsY,"-10.801696777344") -- PosY
table.insert(DropPointsZ,"-23.968751907349") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"288.88687133789") -- PosX
table.insert(DropPointsY,"-484.03179931641") -- PosY
table.insert(DropPointsZ,"-23.968751907349") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"188.32810974121") -- PosX
table.insert(DropPointsY,"201.03848266602") -- PosY
table.insert(DropPointsZ,"232.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"192.78045654297") -- PosX
table.insert(DropPointsY,"-470.36810302734") -- PosY
table.insert(DropPointsZ,"360.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-114.00238037109") -- PosX
table.insert(DropPointsY,"-598.80987548828") -- PosY
table.insert(DropPointsZ,"360.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-650.79425048828") -- PosX
table.insert(DropPointsY,"-472.03125") -- PosY
table.insert(DropPointsZ,"360.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-541.69970703125") -- PosX
table.insert(DropPointsY,"-568.24920654297") -- PosY
table.insert(DropPointsZ,"360.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-212.3837890625") -- PosX
table.insert(DropPointsY,"-379.47955322266") -- PosY
table.insert(DropPointsZ,"360.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-202.89956665039") -- PosX
table.insert(DropPointsY,"321.0002746582") -- PosY
table.insert(DropPointsZ,"232.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"188.77993774414") -- PosX
table.insert(DropPointsY,"477.01086425781") -- PosY
table.insert(DropPointsZ,"360.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"193.75073242188") -- PosX
table.insert(DropPointsY,"-482.4709777832") -- PosY
table.insert(DropPointsZ,"740.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-103.52388763428") -- PosX
table.insert(DropPointsY,"-156.94242858887") -- PosY
table.insert(DropPointsZ,"727.80114746094") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-103.96875") -- PosX
table.insert(DropPointsY,"-319.03732299805") -- PosY
table.insert(DropPointsZ,"728.45239257813") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-661.41766357422") -- PosX
table.insert(DropPointsY,"-517.837890625") -- PosY
table.insert(DropPointsZ,"744.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-679.65325927734") -- PosX
table.insert(DropPointsY,"-649.21209716797") -- PosY
table.insert(DropPointsZ,"744.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-480.15155029297") -- PosX
table.insert(DropPointsY,"-673.76013183594") -- PosY
table.insert(DropPointsZ,"744.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"122.48295593262") -- PosX
table.insert(DropPointsY,"-213.55419921875") -- PosY
table.insert(DropPointsZ,"493.06042480469") -- PosZ