-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"377.42694091797") -- PosX
table.insert(DropPointsY,"-456.35333251953") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"430.75170898438") -- PosX
table.insert(DropPointsY,"267.30004882813") -- PosY
table.insert(DropPointsZ,"-255.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"359.37536621094") -- PosX
table.insert(DropPointsY,"157.60220336914") -- PosY
table.insert(DropPointsZ,"-203.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"458.97021484375") -- PosX
table.insert(DropPointsY,"394.26382446289") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"153.49110412598") -- PosX
table.insert(DropPointsY,"676.41625976563") -- PosY
table.insert(DropPointsZ,"166.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-476.37280273438") -- PosX
table.insert(DropPointsY,"373.40606689453") -- PosY
table.insert(DropPointsZ,"320.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"98.15901184082") -- PosX
table.insert(DropPointsY,"119.32661437988") -- PosY
table.insert(DropPointsZ,"384.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"34.798851013184") -- PosX
table.insert(DropPointsY,"-104.36642456055") -- PosY
table.insert(DropPointsZ,"320.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-489.85900878906") -- PosX
table.insert(DropPointsY,"-304.02731323242") -- PosY
table.insert(DropPointsZ,"320.03125") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"-30.694591522217") -- PosX
table.insert(DropPointsY,"222.22964477539") -- PosY
table.insert(DropPointsZ,"448.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-400.03125") -- PosX
table.insert(DropPointsY,"247.66348266602") -- PosY
table.insert(DropPointsZ,"384.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"42.251438140869") -- PosX
table.insert(DropPointsY,"412.24951171875") -- PosY
table.insert(DropPointsZ,"385.35122680664") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"401.0471496582") -- PosX
table.insert(DropPointsY,"235.2585144043") -- PosY
table.insert(DropPointsZ,"640.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-374.51834106445") -- PosX
table.insert(DropPointsY,"310.87014770508") -- PosY
table.insert(DropPointsZ,"640.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"72.603019714355") -- PosX
table.insert(DropPointsY,"335.93954467773") -- PosY
table.insert(DropPointsZ,"640.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-37.565166473389") -- PosX
table.insert(DropPointsY,"-104.40135955811") -- PosY
table.insert(DropPointsZ,"640.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-120.73854064941") -- PosX
table.insert(DropPointsY,"134.92597961426") -- PosY
table.insert(DropPointsZ,"768.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"97.933753967285") -- PosX
table.insert(DropPointsY,"-123.50494384766") -- PosY
table.insert(DropPointsZ,"1152.03125") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"452.77969360352") -- PosX
table.insert(DropPointsY,"157.98811340332") -- PosY
table.insert(DropPointsZ,"320.03125") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"447.89526367188") -- PosX
table.insert(DropPointsY,"-158.56050109863") -- PosY
table.insert(DropPointsZ,"320.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-434.3974609375") -- PosX
table.insert(DropPointsY,"258.96725463867") -- PosY
table.insert(DropPointsZ,"1344.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-165.40489196777") -- PosX
table.insert(DropPointsY,"434.46838378906") -- PosY
table.insert(DropPointsZ,"1344.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"396.30999755859") -- PosX
table.insert(DropPointsY,"501.31039428711") -- PosY
table.insert(DropPointsZ,"1320.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"967.85589599609") -- PosX
table.insert(DropPointsY,"-224.17057800293") -- PosY
table.insert(DropPointsZ,"1048.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"980.52142333984") -- PosX
table.insert(DropPointsY,"0.70713353157043") -- PosY
table.insert(DropPointsZ,"1048.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1018.6901245117") -- PosX
table.insert(DropPointsY,"-212.82597351074") -- PosY
table.insert(DropPointsZ,"1184.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1.6429482698441") -- PosX
table.insert(DropPointsY,"454.37673950195") -- PosY
table.insert(DropPointsZ,"1280.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"109.02838897705") -- PosX
table.insert(DropPointsY,"276.86575317383") -- PosY
table.insert(DropPointsZ,"1280.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"182.06005859375") -- PosX
table.insert(DropPointsY,"-251.54486083984") -- PosY
table.insert(DropPointsZ,"1368.5112304688") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"179.72055053711") -- PosX
table.insert(DropPointsY,"216.78958129883") -- PosY
table.insert(DropPointsZ,"1408.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-307.86166381836") -- PosX
table.insert(DropPointsY,"-218.28453063965") -- PosY
table.insert(DropPointsZ,"1344.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-490.28805541992") -- PosX
table.insert(DropPointsY,"-408.46853637695") -- PosY
table.insert(DropPointsZ,"1320.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1325.2004394531") -- PosX
table.insert(DropPointsY,"118.40374755859") -- PosY
table.insert(DropPointsZ,"464.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1236.03125") -- PosX
table.insert(DropPointsY,"31.428056716919") -- PosY
table.insert(DropPointsZ,"640.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1029.7666015625") -- PosX
table.insert(DropPointsY,"261.54000854492") -- PosY
table.insert(DropPointsZ,"677.58947753906") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1039.8316650391") -- PosX
table.insert(DropPointsY,"88.991722106934") -- PosY
table.insert(DropPointsZ,"640.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1116.4635009766") -- PosX
table.insert(DropPointsY,"92.053527832031") -- PosY
table.insert(DropPointsZ,"776.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1140.11328125") -- PosX
table.insert(DropPointsY,"313.05523681641") -- PosY
table.insert(DropPointsZ,"776.42022705078") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-969.44836425781") -- PosX
table.insert(DropPointsY,"180.97409057617") -- PosY
table.insert(DropPointsZ,"640.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-763.31329345703") -- PosX
table.insert(DropPointsY,"172.81581115723") -- PosY
table.insert(DropPointsZ,"1096.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-688.55572509766") -- PosX
table.insert(DropPointsY,"126.95275878906") -- PosY
table.insert(DropPointsZ,"297.17065429688") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-651.68127441406") -- PosX
table.insert(DropPointsY,"-336.09887695313") -- PosY
table.insert(DropPointsZ,"-303.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-729.28912353516") -- PosX
table.insert(DropPointsY,"-211.1563873291") -- PosY
table.insert(DropPointsZ,"-87.96875") -- PosZ