-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"-239.4255065918") -- PosX
table.insert(DropPointsY,"-238.60989379883") -- PosY
table.insert(DropPointsZ,"-420.71878051758") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-214.78538513184") -- PosX
table.insert(DropPointsY,"326.63842773438") -- PosY
table.insert(DropPointsZ,"-419.13629150391") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"638.78405761719") -- PosX
table.insert(DropPointsY,"863.51788330078") -- PosY
table.insert(DropPointsZ,"-389.39373779297") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"863.85565185547") -- PosX
table.insert(DropPointsY,"925.18920898438") -- PosY
table.insert(DropPointsZ,"-385.68878173828") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"937.84368896484") -- PosX
table.insert(DropPointsY,"-869.94049072266") -- PosY
table.insert(DropPointsZ,"-392.2887878418") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"710.50317382813") -- PosX
table.insert(DropPointsY,"-933.31756591797") -- PosY
table.insert(DropPointsZ,"-390.43627929688") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-99.250473022461") -- PosX
table.insert(DropPointsY,"-916.83721923828") -- PosY
table.insert(DropPointsZ,"-479.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-865.50396728516") -- PosX
table.insert(DropPointsY,"-932.13409423828") -- PosY
table.insert(DropPointsZ,"-447.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-925.62579345703") -- PosX
table.insert(DropPointsY,"-701.47601318359") -- PosY
table.insert(DropPointsZ,"-428.2887878418") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-904.45111083984") -- PosX
table.insert(DropPointsY,"134.06680297852") -- PosY
table.insert(DropPointsZ,"-357.68878173828") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-641.13781738281") -- PosX
table.insert(DropPointsY,"627.04705810547") -- PosY
table.insert(DropPointsZ,"-447.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"118.06984710693") -- PosX
table.insert(DropPointsY,"-115.97840118408") -- PosY
table.insert(DropPointsZ,"250.95123291016") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"42.765201568604") -- PosX
table.insert(DropPointsY,"92.89892578125") -- PosY
table.insert(DropPointsZ,"418.75122070313") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-55.81649017334") -- PosX
table.insert(DropPointsY,"-70.661720275879") -- PosY
table.insert(DropPointsZ,"442.26373291016") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-83.14958190918") -- PosX
table.insert(DropPointsY,"7.0532703399658") -- PosY
table.insert(DropPointsZ,"-479.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-155.43159484863") -- PosX
table.insert(DropPointsY,"-150.04669189453") -- PosY
table.insert(DropPointsZ,"796.71124267578") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-154.35797119141") -- PosX
table.insert(DropPointsY,"180.27391052246") -- PosY
table.insert(DropPointsZ,"758.72375488281") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1371.8851318359") -- PosX
table.insert(DropPointsY,"1450.41015625") -- PosY
table.insert(DropPointsZ,"-223.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1119.1475830078") -- PosX
table.insert(DropPointsY,"1132.8804931641") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-849.07800292969") -- PosX
table.insert(DropPointsY,"903.31909179688") -- PosY
table.insert(DropPointsZ,"224.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-650.04840087891") -- PosX
table.insert(DropPointsY,"329.05770874023") -- PosY
table.insert(DropPointsZ,"478.88171386719") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-428.59384155273") -- PosX
table.insert(DropPointsY,"15.03246307373") -- PosY
table.insert(DropPointsZ,"590.759765625") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-655.27172851563") -- PosX
table.insert(DropPointsY,"499.44418334961") -- PosY
table.insert(DropPointsZ,"260.28125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1366.4835205078") -- PosX
table.insert(DropPointsY,"-1357.4312744141") -- PosY
table.insert(DropPointsZ,"-159.19874572754") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1097.7277832031") -- PosX
table.insert(DropPointsY,"-1083.1010742188") -- PosY
table.insert(DropPointsZ,"66.751251220703") -- PosZ