-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"259.29400634766") -- PosX
table.insert(DropPointsY,"-1356.8463134766") -- PosY
table.insert(DropPointsZ,"36.863983154297") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"651.92913818359") -- PosX
table.insert(DropPointsY,"-1052.9517822266") -- PosY
table.insert(DropPointsZ,"120.19295501709") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"493.32144165039") -- PosX
table.insert(DropPointsY,"-1059.8937988281") -- PosY
table.insert(DropPointsZ,"68.634666442871") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"973.98321533203") -- PosX
table.insert(DropPointsY,"-1377.3671875") -- PosY
table.insert(DropPointsZ,"28.558986663818") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"205.6309967041") -- PosX
table.insert(DropPointsY,"-442.82543945313") -- PosY
table.insert(DropPointsZ,"26.209506988525") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"207.61585998535") -- PosX
table.insert(DropPointsY,"280.29333496094") -- PosY
table.insert(DropPointsZ,"79.281242370605") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"994.43829345703") -- PosX
table.insert(DropPointsY,"863.84094238281") -- PosY
table.insert(DropPointsZ,"46.279472351074") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"625.08154296875") -- PosX
table.insert(DropPointsY,"1378.4222412109") -- PosY
table.insert(DropPointsZ,"34.864768981934") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"385.78952026367") -- PosX
table.insert(DropPointsY,"1462.4246826172") -- PosY
table.insert(DropPointsZ,"31.852798461914") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"140.14265441895") -- PosX
table.insert(DropPointsY,"1210.2614746094") -- PosY
table.insert(DropPointsZ,"86.377861022949") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"266.4616394043") -- PosX
table.insert(DropPointsY,"-518.75988769531") -- PosY
table.insert(DropPointsZ,"286.96231079102") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"952.60009765625") -- PosX
table.insert(DropPointsY,"219.34010314941") -- PosY
table.insert(DropPointsZ,"56.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-309.50903320313") -- PosX
table.insert(DropPointsY,"-1425.1751708984") -- PosY
table.insert(DropPointsZ,"39.49800491333") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-760.48394775391") -- PosX
table.insert(DropPointsY,"-1350.8857421875") -- PosY
table.insert(DropPointsZ,"2.0959072113037") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1593.6086425781") -- PosX
table.insert(DropPointsY,"-1273.380859375") -- PosY
table.insert(DropPointsZ,"-133.34907531738") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-2407.0979003906") -- PosX
table.insert(DropPointsY,"-1928.1004638672") -- PosY
table.insert(DropPointsZ,"-321.29055786133") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-711.51013183594") -- PosX
table.insert(DropPointsY,"1165.2288818359") -- PosY
table.insert(DropPointsZ,"214.00456237793") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-128.34327697754") -- PosX
table.insert(DropPointsY,"893.77752685547") -- PosY
table.insert(DropPointsZ,"234.7193145752") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"40.187072753906") -- PosX
table.insert(DropPointsY,"-1508.2880859375") -- PosY
table.insert(DropPointsZ,"505.5637512207") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"20.006237030029") -- PosX
table.insert(DropPointsY,"-564.60424804688") -- PosY
table.insert(DropPointsZ,"415.20123291016") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"932.97692871094") -- PosX
table.insert(DropPointsY,"-514.61749267578") -- PosY
table.insert(DropPointsZ,"325.83450317383") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"234.61524963379") -- PosX
table.insert(DropPointsY,"991.28167724609") -- PosY
table.insert(DropPointsZ,"56.654769897461") -- PosZ