-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"628.7626953125") -- PosX
table.insert(DropPointsY,"871.26190185547") -- PosY
table.insert(DropPointsZ,"268.44534301758") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"410.13098144531") -- PosX
table.insert(DropPointsY,"922.91485595703") -- PosY
table.insert(DropPointsZ,"119.97520446777") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"534.78668212891") -- PosX
table.insert(DropPointsY,"1319.2198486328") -- PosY
table.insert(DropPointsZ,"114.84374237061") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"279.36614990234") -- PosX
table.insert(DropPointsY,"969.09912109375") -- PosY
table.insert(DropPointsZ,"117.00923156738") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1241.7897949219") -- PosX
table.insert(DropPointsY,"1735.8635253906") -- PosY
table.insert(DropPointsZ,"56.837051391602") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"816.75720214844") -- PosX
table.insert(DropPointsY,"1061.4689941406") -- PosY
table.insert(DropPointsZ,"-27.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1129.4660644531") -- PosX
table.insert(DropPointsY,"1076.9733886719") -- PosY
table.insert(DropPointsZ,"-27.727420806885") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1367.2592773438") -- PosX
table.insert(DropPointsY,"1724.2921142578") -- PosY
table.insert(DropPointsZ,"-22.862724304199") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"955.70568847656") -- PosX
table.insert(DropPointsY,"1047.15625") -- PosY
table.insert(DropPointsZ,"113.84776306152") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"201.33232116699") -- PosX
table.insert(DropPointsY,"1008.8962402344") -- PosY
table.insert(DropPointsZ,"-25.036249160767") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"401.57040405273") -- PosX
table.insert(DropPointsY,"911.48712158203") -- PosY
table.insert(DropPointsZ,"256.39916992188") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"499.64282226563") -- PosX
table.insert(DropPointsY,"1322.9412841797") -- PosY
table.insert(DropPointsZ,"258.67916870117") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"279.91821289063") -- PosX
table.insert(DropPointsY,"989.76690673828") -- PosY
table.insert(DropPointsZ,"255.49171447754") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"378.60577392578") -- PosX
table.insert(DropPointsY,"964.71105957031") -- PosY
table.insert(DropPointsZ,"321.67926025391") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"729.50573730469") -- PosX
table.insert(DropPointsY,"1066.9938964844") -- PosY
table.insert(DropPointsZ,"343.21173095703") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"935.85455322266") -- PosX
table.insert(DropPointsY,"817.08978271484") -- PosY
table.insert(DropPointsZ,"-17.072298049927") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-17.47597694397") -- PosX
table.insert(DropPointsY,"781.79406738281") -- PosY
table.insert(DropPointsZ,"34.311237335205") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"611.78021240234") -- PosX
table.insert(DropPointsY,"1171.3735351563") -- PosY
table.insert(DropPointsZ,"466.00119018555") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1031.6651611328") -- PosX
table.insert(DropPointsY,"1485.5729980469") -- PosY
table.insert(DropPointsZ,"44.995414733887") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"545.77227783203") -- PosX
table.insert(DropPointsY,"861.58276367188") -- PosY
table.insert(DropPointsZ,"102.72373962402") -- PosZ