-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"864.36962890625") -- PosX
table.insert(DropPointsY,"298.27395629883") -- PosY
table.insert(DropPointsZ,"-76.375686645508") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1023.3739624023") -- PosX
table.insert(DropPointsY,"-40.844863891602") -- PosY
table.insert(DropPointsZ,"-127.71875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"992.70489501953") -- PosX
table.insert(DropPointsY,"-605.87768554688") -- PosY
table.insert(DropPointsZ,"-117.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"314.73123168945") -- PosX
table.insert(DropPointsY,"342.2600402832") -- PosY
table.insert(DropPointsZ,"-95.288757324219") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"657.94683837891") -- PosX
table.insert(DropPointsY,"92.926483154297") -- PosY
table.insert(DropPointsZ,"-89.476257324219") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"475.01675415039") -- PosX
table.insert(DropPointsY,"340.02810668945") -- PosY
table.insert(DropPointsZ,"-61.686023712158") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"62.67008972168") -- PosX
table.insert(DropPointsY,"-71.41088104248") -- PosY
table.insert(DropPointsZ,"-90.136260986328") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-290.3681640625") -- PosX
table.insert(DropPointsY,"-115.76711273193") -- PosY
table.insert(DropPointsZ,"-48.494213104248") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-39.592281341553") -- PosX
table.insert(DropPointsY,"-297.41226196289") -- PosY
table.insert(DropPointsZ,"19.711246490479") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"58.85729598999") -- PosX
table.insert(DropPointsY,"230.15502929688") -- PosY
table.insert(DropPointsZ,"57.563758850098") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"443.88140869141") -- PosX
table.insert(DropPointsY,"383.00744628906") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"94.123573303223") -- PosX
table.insert(DropPointsY,"-305.97476196289") -- PosY
table.insert(DropPointsZ,"5.4237418174744") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1046.8530273438") -- PosX
table.insert(DropPointsY,"-46.727939605713") -- PosY
table.insert(DropPointsZ,"62.746250152588") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1002.8801879883") -- PosX
table.insert(DropPointsY,"263.71264648438") -- PosY
table.insert(DropPointsZ,"60.863758087158") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"575.03845214844") -- PosX
table.insert(DropPointsY,"505.10089111328") -- PosY
table.insert(DropPointsZ,"60.863758087158") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1086.8957519531") -- PosX
table.insert(DropPointsY,"-128.9097442627") -- PosY
table.insert(DropPointsZ,"66.751251220703") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"812.88262939453") -- PosX
table.insert(DropPointsY,"-670.91381835938") -- PosY
table.insert(DropPointsZ,"60.121253967285") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"850.96875") -- PosX
table.insert(DropPointsY,"-915.40814208984") -- PosY
table.insert(DropPointsZ,"-87.376251220703") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"814.93005371094") -- PosX
table.insert(DropPointsY,"-795.38238525391") -- PosY
table.insert(DropPointsZ,"-90.136260986328") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"884.13482666016") -- PosX
table.insert(DropPointsY,"-395.12713623047") -- PosY
table.insert(DropPointsZ,"224.57095336914") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"642.42877197266") -- PosX
table.insert(DropPointsY,"171.85354614258") -- PosY
table.insert(DropPointsZ,"137.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"846.83502197266") -- PosX
table.insert(DropPointsY,"277.97775268555") -- PosY
table.insert(DropPointsZ,"137.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"302.4990234375") -- PosX
table.insert(DropPointsY,"123.2405166626") -- PosY
table.insert(DropPointsZ,"183.62326049805") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"357.31042480469") -- PosX
table.insert(DropPointsY,"417.06674194336") -- PosY
table.insert(DropPointsZ,"158.5637512207") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"96.291648864746") -- PosX
table.insert(DropPointsY,"-284.63824462891") -- PosY
table.insert(DropPointsZ,"137.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"111.657371521") -- PosX
table.insert(DropPointsY,"396.99542236328") -- PosY
table.insert(DropPointsZ,"137.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"743.97839355469") -- PosX
table.insert(DropPointsY,"411.17379760742") -- PosY
table.insert(DropPointsZ,"154.72375488281") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"748.03137207031") -- PosX
table.insert(DropPointsY,"-89.97200012207") -- PosY
table.insert(DropPointsZ,"227.01147460938") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-35.776607513428") -- PosX
table.insert(DropPointsY,"-1395.3155517578") -- PosY
table.insert(DropPointsZ,"-137.64570617676") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-611.42932128906") -- PosX
table.insert(DropPointsY,"-1484.296875") -- PosY
table.insert(DropPointsZ,"-138.2544708252") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-808.85443115234") -- PosX
table.insert(DropPointsY,"-423.00601196289") -- PosY
table.insert(DropPointsZ,"-147.84259033203") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"726.90441894531") -- PosX
table.insert(DropPointsY,"763.24536132813") -- PosY
table.insert(DropPointsZ,"-146.1014251709") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1234.8937988281") -- PosX
table.insert(DropPointsY,"-191.85418701172") -- PosY
table.insert(DropPointsZ,"-100.48351287842") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1181.7041015625") -- PosX
table.insert(DropPointsY,"-1114.3179931641") -- PosY
table.insert(DropPointsZ,"-153.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-470.81463623047") -- PosX
table.insert(DropPointsY,"-836.46478271484") -- PosY
table.insert(DropPointsZ,"-97.043739318848") -- PosZ