-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"1232.6557617188") -- PosX
table.insert(DropPointsY,"-591.81286621094") -- PosY
table.insert(DropPointsZ,"4.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"842.60528564453") -- PosX
table.insert(DropPointsY,"-576.49945068359") -- PosY
table.insert(DropPointsZ,"4.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"359.07266235352") -- PosX
table.insert(DropPointsY,"-1029.4256591797") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"794.76782226563") -- PosX
table.insert(DropPointsY,"-1031.3405761719") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"872.45550537109") -- PosX
table.insert(DropPointsY,"-935.64318847656") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1363.9709472656") -- PosX
table.insert(DropPointsY,"-675.38647460938") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"977.47912597656") -- PosX
table.insert(DropPointsY,"-477.61010742188") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"352.96664428711") -- PosX
table.insert(DropPointsY,"-297.30499267578") -- PosY
table.insert(DropPointsZ,"72.236465454102") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"276.7275390625") -- PosX
table.insert(DropPointsY,"-399.67642211914") -- PosY
table.insert(DropPointsZ,"9.0313167572021") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-141.25624084473") -- PosX
table.insert(DropPointsY,"-362.22634887695") -- PosY
table.insert(DropPointsZ,"45.996215820313") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"245.46997070313") -- PosX
table.insert(DropPointsY,"-1114.5849609375") -- PosY
table.insert(DropPointsZ,"29.803007125854") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"240.61367797852") -- PosX
table.insert(DropPointsY,"-213.94459533691") -- PosY
table.insert(DropPointsZ,"37.571907043457") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"341.41897583008") -- PosX
table.insert(DropPointsY,"-229.63352966309") -- PosY
table.insert(DropPointsZ,"192.54025268555") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"613.75866699219") -- PosX
table.insert(DropPointsY,"-442.28143310547") -- PosY
table.insert(DropPointsZ,"256.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1278.6214599609") -- PosX
table.insert(DropPointsY,"-704.72552490234") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"969.31671142578") -- PosX
table.insert(DropPointsY,"-931.02349853516") -- PosY
table.insert(DropPointsZ,"256.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-79.952278137207") -- PosX
table.insert(DropPointsY,"-1040.4949951172") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-68.210807800293") -- PosX
table.insert(DropPointsY,"-284.02908325195") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-415.30026245117") -- PosX
table.insert(DropPointsY,"-507.36798095703") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-608.12457275391") -- PosX
table.insert(DropPointsY,"-298.85107421875") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-591.28820800781") -- PosX
table.insert(DropPointsY,"-525.50714111328") -- PosY
table.insert(DropPointsZ,"332.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-249.82402038574") -- PosX
table.insert(DropPointsY,"-339.28811645508") -- PosY
table.insert(DropPointsZ,"332.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-408.34338378906") -- PosX
table.insert(DropPointsY,"-816.87243652344") -- PosY
table.insert(DropPointsZ,"332.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-599.94635009766") -- PosX
table.insert(DropPointsY,"-1033.4891357422") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-416.8688659668") -- PosX
table.insert(DropPointsY,"-814.43914794922") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-323.34463500977") -- PosX
table.insert(DropPointsY,"-845.33215332031") -- PosY
table.insert(DropPointsZ,"261.28900146484") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-409.6203918457") -- PosX
table.insert(DropPointsY,"-387.97964477539") -- PosY
table.insert(DropPointsZ,"478.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"968.78375244141") -- PosX
table.insert(DropPointsY,"-648.91729736328") -- PosY
table.insert(DropPointsZ,"554.35467529297") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"204.97621154785") -- PosX
table.insert(DropPointsY,"-353.00747680664") -- PosY
table.insert(DropPointsZ,"256.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1222.3878173828") -- PosX
table.insert(DropPointsY,"-84.668746948242") -- PosY
table.insert(DropPointsZ,"110.23780822754") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"778.94384765625") -- PosX
table.insert(DropPointsY,"-300.58801269531") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ