-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"-476.07012939453") -- PosX
table.insert(DropPointsY,"1060.2060546875") -- PosY
table.insert(DropPointsZ,"160.53091430664") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-995.21447753906") -- PosX
table.insert(DropPointsY,"1025.3043212891") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-852.58843994141") -- PosX
table.insert(DropPointsY,"68.681716918945") -- PosY
table.insert(DropPointsZ,"32.161235809326") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-359.85388183594") -- PosX
table.insert(DropPointsY,"59.45259475708") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-360.57077026367") -- PosX
table.insert(DropPointsY,"553.85552978516") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-221.01516723633") -- PosX
table.insert(DropPointsY,"64.768783569336") -- PosY
table.insert(DropPointsZ,"117.39981842041") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"215.9446105957") -- PosX
table.insert(DropPointsY,"221.49942016602") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"340.73645019531") -- PosX
table.insert(DropPointsY,"225.47625732422") -- PosY
table.insert(DropPointsZ,"82.328765869141") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"794.98205566406") -- PosX
table.insert(DropPointsY,"174.97901916504") -- PosY
table.insert(DropPointsZ,"57.563758850098") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1480.7263183594") -- PosX
table.insert(DropPointsY,"96.904411315918") -- PosY
table.insert(DropPointsZ,"79.205459594727") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1831.0654296875") -- PosX
table.insert(DropPointsY,"48.003025054932") -- PosY
table.insert(DropPointsZ,"69.323753356934") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"998.28082275391") -- PosX
table.insert(DropPointsY,"843.09228515625") -- PosY
table.insert(DropPointsZ,"63.623748779297") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"377.61352539063") -- PosX
table.insert(DropPointsY,"893.51489257813") -- PosY
table.insert(DropPointsZ,"65.55980682373") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"62.788242340088") -- PosX
table.insert(DropPointsY,"543.85559082031") -- PosY
table.insert(DropPointsZ,"19.171251296997") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"57.070919036865") -- PosX
table.insert(DropPointsY,"1445.2111816406") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"40.982120513916") -- PosX
table.insert(DropPointsY,"1178.4521484375") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1715.5006103516") -- PosX
table.insert(DropPointsY,"948.20666503906") -- PosY
table.insert(DropPointsZ,"78.455459594727") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1526.5479736328") -- PosX
table.insert(DropPointsY,"1377.1165771484") -- PosY
table.insert(DropPointsZ,"77.877960205078") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1268.8781738281") -- PosX
table.insert(DropPointsY,"716.90765380859") -- PosY
table.insert(DropPointsZ,"190.25045776367") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1747.3341064453") -- PosX
table.insert(DropPointsY,"1281.1617431641") -- PosY
table.insert(DropPointsZ,"128.8210144043") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1842.5242919922") -- PosX
table.insert(DropPointsY,"716.23217773438") -- PosY
table.insert(DropPointsZ,"138.47044372559") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1884.7347412109") -- PosX
table.insert(DropPointsY,"764.69006347656") -- PosY
table.insert(DropPointsZ,"294.29446411133") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1864.1427001953") -- PosX
table.insert(DropPointsY,"2021.1010742188") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1170.3725585938") -- PosX
table.insert(DropPointsY,"1857.2143554688") -- PosY
table.insert(DropPointsZ,"302.42373657227") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1089.0915527344") -- PosX
table.insert(DropPointsY,"2835.3203125") -- PosY
table.insert(DropPointsZ,"272.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2019.0445556641") -- PosX
table.insert(DropPointsY,"2854.6201171875") -- PosY
table.insert(DropPointsZ,"272.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1978.740234375") -- PosX
table.insert(DropPointsY,"759.91906738281") -- PosY
table.insert(DropPointsZ,"57.005443572998") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1966.0797119141") -- PosX
table.insert(DropPointsY,"2344.5241699219") -- PosY
table.insert(DropPointsZ,"70.536422729492") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1086.4691162109") -- PosX
table.insert(DropPointsY,"3100.3474121094") -- PosY
table.insert(DropPointsZ,"74.158256530762") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1832.4769287109") -- PosX
table.insert(DropPointsY,"2706.7861328125") -- PosY
table.insert(DropPointsZ,"60.001258850098") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1007.9882202148") -- PosX
table.insert(DropPointsY,"1177.8544921875") -- PosY
table.insert(DropPointsZ,"28.801240921021") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-884.14013671875") -- PosX
table.insert(DropPointsY,"1446.8157958984") -- PosY
table.insert(DropPointsZ,"190.39367675781") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-208.47071838379") -- PosX
table.insert(DropPointsY,"1462.5285644531") -- PosY
table.insert(DropPointsZ,"55.711254119873") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-404.48791503906") -- PosX
table.insert(DropPointsY,"3101.7265625") -- PosY
table.insert(DropPointsZ,"55.171257019043") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-788.42230224609") -- PosX
table.insert(DropPointsY,"1558.6899414063") -- PosY
table.insert(DropPointsZ,"51.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"736.67895507813") -- PosX
table.insert(DropPointsY,"2648.552734375") -- PosY
table.insert(DropPointsZ,"21.563745498657") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"925.86437988281") -- PosX
table.insert(DropPointsY,"3140.0764160156") -- PosY
table.insert(DropPointsZ,"60.633399963379") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"873.92779541016") -- PosX
table.insert(DropPointsY,"3202.96875") -- PosY
table.insert(DropPointsZ,"287.38314819336") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1536.1301269531") -- PosX
table.insert(DropPointsY,"1488.0902099609") -- PosY
table.insert(DropPointsZ,"45.331230163574") -- PosZ