-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"619.18725585938") -- PosX
table.insert(DropPointsY,"-558.54803466797") -- PosY
table.insert(DropPointsZ,"-76.476257324219") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-42.264797210693") -- PosX
table.insert(DropPointsY,"-411.8854675293") -- PosY
table.insert(DropPointsZ,"69.263748168945") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"6.5121994018555") -- PosX
table.insert(DropPointsY,"-212.93684387207") -- PosY
table.insert(DropPointsZ,"69.361251831055") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-85.949356079102") -- PosX
table.insert(DropPointsY,"-76.989990234375") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"476.12518310547") -- PosX
table.insert(DropPointsY,"-74.985458374023") -- PosY
table.insert(DropPointsZ,"61.528179168701") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"467.66244506836") -- PosX
table.insert(DropPointsY,"-228.0897064209") -- PosY
table.insert(DropPointsZ,"132.86372375488") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"651.17059326172") -- PosX
table.insert(DropPointsY,"-297.46813964844") -- PosY
table.insert(DropPointsZ,"164.59617614746") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-108.31553649902") -- PosX
table.insert(DropPointsY,"-351.5654296875") -- PosY
table.insert(DropPointsZ,"217.35804748535") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-50.078170776367") -- PosX
table.insert(DropPointsY,"-219.21002197266") -- PosY
table.insert(DropPointsZ,"208.16375732422") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"432.83258056641") -- PosX
table.insert(DropPointsY,"-16.340921401978") -- PosY
table.insert(DropPointsZ,"144.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-78.824638366699") -- PosX
table.insert(DropPointsY,"-16.034866333008") -- PosY
table.insert(DropPointsZ,"213.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1353.4305419922") -- PosX
table.insert(DropPointsY,"-501.85009765625") -- PosY
table.insert(DropPointsZ,"161.72375488281") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1347.736328125") -- PosX
table.insert(DropPointsY,"-835.77825927734") -- PosY
table.insert(DropPointsZ,"19.711246490479") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1484.8845214844") -- PosX
table.insert(DropPointsY,"-541.42749023438") -- PosY
table.insert(DropPointsZ,"29.843738555908") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"625.97729492188") -- PosX
table.insert(DropPointsY,"-321.62692260742") -- PosY
table.insert(DropPointsZ,"26.311243057251") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1279.8189697266") -- PosX
table.insert(DropPointsY,"525.05285644531") -- PosY
table.insert(DropPointsZ,"32.817989349365") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-943.89727783203") -- PosX
table.insert(DropPointsY,"364.06964111328") -- PosY
table.insert(DropPointsZ,"69.263748168945") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1101.4438476563") -- PosX
table.insert(DropPointsY,"-568.04937744141") -- PosY
table.insert(DropPointsZ,"69.151252746582") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-274.82550048828") -- PosX
table.insert(DropPointsY,"-287.58877563477") -- PosY
table.insert(DropPointsZ,"45.563751220703") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"270.95755004883") -- PosX
table.insert(DropPointsY,"-799.86712646484") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1078.1007080078") -- PosX
table.insert(DropPointsY,"-277.82736206055") -- PosY
table.insert(DropPointsZ,"112.85202026367") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-704.89068603516") -- PosX
table.insert(DropPointsY,"-934.00378417969") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1005.8030395508") -- PosX
table.insert(DropPointsY,"-704.80157470703") -- PosY
table.insert(DropPointsZ,"62.911251068115") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-953.59375") -- PosX
table.insert(DropPointsY,"-257.64846801758") -- PosY
table.insert(DropPointsZ,"64.801246643066") -- PosZ