-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"20.937088012695") -- PosX
table.insert(DropPointsY,"1203.4270019531") -- PosY
table.insert(DropPointsZ,"-134.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"72.413688659668") -- PosX
table.insert(DropPointsY,"1181.4737548828") -- PosY
table.insert(DropPointsZ,"-101.21559143066") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-156.46644592285") -- PosX
table.insert(DropPointsY,"1541.8967285156") -- PosY
table.insert(DropPointsZ,"-134.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-308.62899780273") -- PosX
table.insert(DropPointsY,"1157.7907714844") -- PosY
table.insert(DropPointsZ,"-85.616622924805") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"-355.90982055664") -- PosX
table.insert(DropPointsY,"1499.0892333984") -- PosY
table.insert(DropPointsZ,"-134.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-680.40045166016") -- PosX
table.insert(DropPointsY,"1379.1057128906") -- PosY
table.insert(DropPointsZ,"-134.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-344.24993896484") -- PosX
table.insert(DropPointsY,"1610.8199462891") -- PosY
table.insert(DropPointsZ,"54.481143951416") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-279.31686401367") -- PosX
table.insert(DropPointsY,"1432.7980957031") -- PosY
table.insert(DropPointsZ,"47.003952026367") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"-1541.8565673828") -- PosX
table.insert(DropPointsY,"108.13890838623") -- PosY
table.insert(DropPointsZ,"-7.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-224.07298278809") -- PosX
table.insert(DropPointsY,"1605.4020996094") -- PosY
table.insert(DropPointsZ,"-7.96875") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"-1545.3260498047") -- PosX
table.insert(DropPointsY,"1105.4011230469") -- PosY
table.insert(DropPointsZ,"-7.9779834747314") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-164.3606262207") -- PosX
table.insert(DropPointsY,"1439.3851318359") -- PosY
table.insert(DropPointsZ,"-7.96875") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"-1555.5727539063") -- PosX
table.insert(DropPointsY,"2348.8312988281") -- PosY
table.insert(DropPointsZ,"-8.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"99.307159423828") -- PosX
table.insert(DropPointsY,"1411.4720458984") -- PosY
table.insert(DropPointsZ,"46.392345428467") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"68.486259460449") -- PosX
table.insert(DropPointsY,"1176.6672363281") -- PosY
table.insert(DropPointsZ,"33.907253265381") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"-156.23847961426") -- PosX
table.insert(DropPointsY,"2387.5319824219") -- PosY
table.insert(DropPointsZ,"-7.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"375.96875") -- PosX
table.insert(DropPointsY,"896.00732421875") -- PosY
table.insert(DropPointsZ,"-7.96875") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"1202.1655273438") -- PosX
table.insert(DropPointsY,"2391.5979003906") -- PosY
table.insert(DropPointsZ,"-7.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"375.25241088867") -- PosX
table.insert(DropPointsY,"1268.0655517578") -- PosY
table.insert(DropPointsZ,"-7.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"365.72756958008") -- PosX
table.insert(DropPointsY,"1607.1539306641") -- PosY
table.insert(DropPointsZ,"-7.9687519073486") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-305.24377441406") -- PosX
table.insert(DropPointsY,"914.51031494141") -- PosY
table.insert(DropPointsZ,"-7.96875") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"-67.338264465332") -- PosX
table.insert(DropPointsY,"117.81021118164") -- PosY
table.insert(DropPointsZ,"-5.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-457.90591430664") -- PosX
table.insert(DropPointsY,"1107.4997558594") -- PosY
table.insert(DropPointsZ,"-7.5033588409424") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"532.83361816406") -- PosX
table.insert(DropPointsY,"113.29895019531") -- PosY
table.insert(DropPointsZ,"-5.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-662.67620849609") -- PosX
table.insert(DropPointsY,"1234.2019042969") -- PosY
table.insert(DropPointsZ,"-7.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-501.04986572266") -- PosX
table.insert(DropPointsY,"1295.4022216797") -- PosY
table.insert(DropPointsZ,"-7.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-509.12576293945") -- PosX
table.insert(DropPointsY,"1291.6987304688") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-321.77450561523") -- PosX
table.insert(DropPointsY,"1610.9857177734") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-336.2451171875") -- PosX
table.insert(DropPointsY,"914.33856201172") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-676.76324462891") -- PosX
table.insert(DropPointsY,"1239.96875") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"127.28922271729") -- PosX
table.insert(DropPointsY,"909.64520263672") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"340.65512084961") -- PosX
table.insert(DropPointsY,"1623.96875") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"59.740245819092") -- PosX
table.insert(DropPointsY,"1504.4190673828") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"350.05187988281") -- PosX
table.insert(DropPointsY,"926.42138671875") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"-409.87258911133") -- PosX
table.insert(DropPointsY,"1168.076171875") -- PosY
table.insert(DropPointsZ,"10.896148681641") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"214.53909301758") -- PosX
table.insert(DropPointsY,"1239.5009765625") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"-407.80288696289") -- PosX
table.insert(DropPointsY,"1221.9462890625") -- PosY
table.insert(DropPointsZ,"10.9830493927") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-77.181488037109") -- PosX
table.insert(DropPointsY,"1378.1263427734") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-12.405774116516") -- PosX
table.insert(DropPointsY,"1616.1209716797") -- PosY
table.insert(DropPointsZ,"128.49409484863") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"347.35760498047") -- PosX
table.insert(DropPointsY,"1499.4809570313") -- PosY
table.insert(DropPointsZ,"256.03125") -- PosZ

-- Added by Ywa
table.insert(DropPointsX,"144.47467041016") -- PosX
table.insert(DropPointsY,"998.18908691406") -- PosY
table.insert(DropPointsZ,"256.03125") -- PosZ