-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"734.44116210938") -- PosX
table.insert(DropPointsY,"-346.49969482422") -- PosY
table.insert(DropPointsZ,"272.29888916016") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"616.46826171875") -- PosX
table.insert(DropPointsY,"-310.64300537109") -- PosY
table.insert(DropPointsZ,"268.39349365234") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"563.30218505859") -- PosX
table.insert(DropPointsY,"115.28433227539") -- PosY
table.insert(DropPointsZ,"208.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"637.14654541016") -- PosX
table.insert(DropPointsY,"-449.26718139648") -- PosY
table.insert(DropPointsZ,"343.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"893.17254638672") -- PosX
table.insert(DropPointsY,"149.02070617676") -- PosY
table.insert(DropPointsZ,"343.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"631.54644775391") -- PosX
table.insert(DropPointsY,"117.9831237793") -- PosY
table.insert(DropPointsZ,"343.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"979.56011962891") -- PosX
table.insert(DropPointsY,"31.032810211182") -- PosY
table.insert(DropPointsZ,"272.95687866211") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"984.93682861328") -- PosX
table.insert(DropPointsY,"-345.96832275391") -- PosY
table.insert(DropPointsZ,"299.33679199219") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"763.93499755859") -- PosX
table.insert(DropPointsY,"24.21489906311") -- PosY
table.insert(DropPointsZ,"208.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"545.07836914063") -- PosX
table.insert(DropPointsY,"-257.17233276367") -- PosY
table.insert(DropPointsZ,"80.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"642.9931640625") -- PosX
table.insert(DropPointsY,"-472.16677856445") -- PosY
table.insert(DropPointsZ,"80.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"547.134765625") -- PosX
table.insert(DropPointsY,"-208.59573364258") -- PosY
table.insert(DropPointsZ,"80.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"819.24365234375") -- PosX
table.insert(DropPointsY,"-256.20217895508") -- PosY
table.insert(DropPointsZ,"80.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"788.03125") -- PosX
table.insert(DropPointsY,"-405.74203491211") -- PosY
table.insert(DropPointsZ,"139.44723510742") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"864.89282226563") -- PosX
table.insert(DropPointsY,"108.96875") -- PosY
table.insert(DropPointsZ,"144.95687866211") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"567.84735107422") -- PosX
table.insert(DropPointsY,"-132.62142944336") -- PosY
table.insert(DropPointsZ,"4.2626495361328") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"829.84887695313") -- PosX
table.insert(DropPointsY,"-166.11221313477") -- PosY
table.insert(DropPointsZ,"-63.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"993.82403564453") -- PosX
table.insert(DropPointsY,"-392.6611328125") -- PosY
table.insert(DropPointsZ,"80.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"261.2825012207") -- PosX
table.insert(DropPointsY,"-895.00146484375") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"357.0383605957") -- PosX
table.insert(DropPointsY,"-1040.3927001953") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1237.2202148438") -- PosX
table.insert(DropPointsY,"-1754.7850341797") -- PosY
table.insert(DropPointsZ,"186.71899414063") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1321.8315429688") -- PosX
table.insert(DropPointsY,"-1531.7667236328") -- PosY
table.insert(DropPointsZ,"147.45245361328") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1210.5244140625") -- PosX
table.insert(DropPointsY,"-1352.7274169922") -- PosY
table.insert(DropPointsZ,"204.07217407227") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1079.9205322266") -- PosX
table.insert(DropPointsY,"-971.82489013672") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"868.693359375") -- PosX
table.insert(DropPointsY,"-589.552734375") -- PosY
table.insert(DropPointsZ,"130.95687866211") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1349.9897460938") -- PosX
table.insert(DropPointsY,"952.31390380859") -- PosY
table.insert(DropPointsZ,"119.86596679688") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"658.29833984375") -- PosX
table.insert(DropPointsY,"623.25677490234") -- PosY
table.insert(DropPointsZ,"102.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"778.25054931641") -- PosX
table.insert(DropPointsY,"228.61663818359") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"71.324821472168") -- PosX
table.insert(DropPointsY,"360.59997558594") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"42.428352355957") -- PosX
table.insert(DropPointsY,"-118.48157501221") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"837.58636474609") -- PosX
table.insert(DropPointsY,"-29.288835525513") -- PosY
table.insert(DropPointsZ,"-341.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1376.5007324219") -- PosX
table.insert(DropPointsY,"314.97082519531") -- PosY
table.insert(DropPointsZ,"-341.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1550.0374755859") -- PosX
table.insert(DropPointsY,"173.97235107422") -- PosY
table.insert(DropPointsZ,"-287.81869506836") -- PosZ