-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"82.806335449219") -- PosX
table.insert(DropPointsY,"665.80517578125") -- PosY
table.insert(DropPointsZ,"-64.136253356934") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-46.556694030762") -- PosX
table.insert(DropPointsY,"134.36672973633") -- PosY
table.insert(DropPointsZ,"-64.136253356934") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-192.32926940918") -- PosX
table.insert(DropPointsY,"427.03411865234") -- PosY
table.insert(DropPointsZ,"-67.436248779297") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-242.80839538574") -- PosX
table.insert(DropPointsY,"506.64691162109") -- PosY
table.insert(DropPointsZ,"-57.798748016357") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-255.4055480957") -- PosX
table.insert(DropPointsY,"883.14886474609") -- PosY
table.insert(DropPointsZ,"-22.248746871948") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-26.279432296753") -- PosX
table.insert(DropPointsY,"728.27691650391") -- PosY
table.insert(DropPointsZ,"-17.040277481079") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"532.08624267578") -- PosX
table.insert(DropPointsY,"442.49255371094") -- PosY
table.insert(DropPointsZ,"-7.5551037788391") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"531.42810058594") -- PosX
table.insert(DropPointsY,"206.16011047363") -- PosY
table.insert(DropPointsZ,"-59.156253814697") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"154.64653015137") -- PosX
table.insert(DropPointsY,"132.67449951172") -- PosY
table.insert(DropPointsZ,"-71.276252746582") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"27.694948196411") -- PosX
table.insert(DropPointsY,"381.021484375") -- PosY
table.insert(DropPointsZ,"-23.156246185303") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"220.01658630371") -- PosX
table.insert(DropPointsY,"378.0280456543") -- PosY
table.insert(DropPointsZ,"-20.336246490479") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"355.66516113281") -- PosX
table.insert(DropPointsY,"705.13360595703") -- PosY
table.insert(DropPointsZ,"71.863746643066") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"366.22381591797") -- PosX
table.insert(DropPointsY,"252.51823425293") -- PosY
table.insert(DropPointsZ,"105.60626220703") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"82.553581237793") -- PosX
table.insert(DropPointsY,"386.20626831055") -- PosY
table.insert(DropPointsZ,"109.3112411499") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"197.07144165039") -- PosX
table.insert(DropPointsY,"239.99110412598") -- PosY
table.insert(DropPointsZ,"116.32375335693") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"204.18646240234") -- PosX
table.insert(DropPointsY,"634.96417236328") -- PosY
table.insert(DropPointsZ,"116.12543487549") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"26.384496688843") -- PosX
table.insert(DropPointsY,"496.45306396484") -- PosY
table.insert(DropPointsZ,"107.86373901367") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"262.66897583008") -- PosX
table.insert(DropPointsY,"692.08636474609") -- PosY
table.insert(DropPointsZ,"101.62372589111") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"391.43466186523") -- PosX
table.insert(DropPointsY,"130.98266601563") -- PosY
table.insert(DropPointsZ,"-88.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"643.02307128906") -- PosX
table.insert(DropPointsY,"923.43475341797") -- PosY
table.insert(DropPointsZ,"-224.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"55.669624328613") -- PosX
table.insert(DropPointsY,"789.82122802734") -- PosY
table.insert(DropPointsZ,"-224.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"387.68988037109") -- PosX
table.insert(DropPointsY,"119.18670654297") -- PosY
table.insert(DropPointsZ,"110.83953094482") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"142.60089111328") -- PosX
table.insert(DropPointsY,"803.84649658203") -- PosY
table.insert(DropPointsZ,"122.90042877197") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"204.78974914551") -- PosX
table.insert(DropPointsY,"518.22216796875") -- PosY
table.insert(DropPointsZ,"415.62002563477") -- PosZ