-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"-305.30969238281") -- PosX
table.insert(DropPointsY,"-486.35861206055") -- PosY
table.insert(DropPointsZ,"113.77404022217") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1006.3264770508") -- PosX
table.insert(DropPointsY,"-951.77551269531") -- PosY
table.insert(DropPointsZ,"104.5479888916") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1513.3236083984") -- PosX
table.insert(DropPointsY,"-924.51641845703") -- PosY
table.insert(DropPointsZ,"135.38471984863") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1833.4967041016") -- PosX
table.insert(DropPointsY,"-734.02770996094") -- PosY
table.insert(DropPointsZ,"156.36549377441") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-2137.89453125") -- PosX
table.insert(DropPointsY,"-1064.9575195313") -- PosY
table.insert(DropPointsZ,"259.82373046875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-2278.9155273438") -- PosX
table.insert(DropPointsY,"-1418.9763183594") -- PosY
table.insert(DropPointsZ,"143.78112792969") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-2069.5373535156") -- PosX
table.insert(DropPointsY,"-1679.1735839844") -- PosY
table.insert(DropPointsZ,"166.67364501953") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-2069.6452636719") -- PosX
table.insert(DropPointsY,"-2050.1459960938") -- PosY
table.insert(DropPointsZ,"129.20304870605") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-2535.0764160156") -- PosX
table.insert(DropPointsY,"-1786.5805664063") -- PosY
table.insert(DropPointsZ,"88.589889526367") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1271.6245117188") -- PosX
table.insert(DropPointsY,"-1379.9957275391") -- PosY
table.insert(DropPointsZ,"249.50128173828") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-299.12817382813") -- PosX
table.insert(DropPointsY,"-2229.7307128906") -- PosY
table.insert(DropPointsZ,"150.38700866699") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1158.3911132813") -- PosX
table.insert(DropPointsY,"-2560.7077636719") -- PosY
table.insert(DropPointsZ,"55.205513000488") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1920.1010742188") -- PosX
table.insert(DropPointsY,"-2148.4123535156") -- PosY
table.insert(DropPointsZ,"82.628898620605") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-193.38005065918") -- PosX
table.insert(DropPointsY,"-119.96875") -- PosY
table.insert(DropPointsZ,"285.03121948242") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"15.156769752502") -- PosX
table.insert(DropPointsY,"85.682563781738") -- PosY
table.insert(DropPointsZ,"452.86370849609") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-362.23001098633") -- PosX
table.insert(DropPointsY,"140.35539245605") -- PosY
table.insert(DropPointsZ,"450.34371948242") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-338.85382080078") -- PosX
table.insert(DropPointsY,"-71.320411682129") -- PosY
table.insert(DropPointsZ,"448.55120849609") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-140.4137878418") -- PosX
table.insert(DropPointsY,"-54.292037963867") -- PosY
table.insert(DropPointsZ,"461.26373291016") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-27.351621627808") -- PosX
table.insert(DropPointsY,"-890.76104736328") -- PosY
table.insert(DropPointsZ,"363.28121948242") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-51.728378295898") -- PosX
table.insert(DropPointsY,"-1240.4992675781") -- PosY
table.insert(DropPointsZ,"497.56369018555") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-48.008880615234") -- PosX
table.insert(DropPointsY,"-1875.09375") -- PosY
table.insert(DropPointsZ,"496.55111694336") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-181.58935546875") -- PosX
table.insert(DropPointsY,"-2480.3857421875") -- PosY
table.insert(DropPointsZ,"433.52703857422") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-351.3576965332") -- PosX
table.insert(DropPointsY,"-3251.2834472656") -- PosY
table.insert(DropPointsZ,"476.24160766602") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-669.33355712891") -- PosX
table.insert(DropPointsY,"-3424.6418457031") -- PosY
table.insert(DropPointsZ,"334.75122070313") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1059.6076660156") -- PosX
table.insert(DropPointsY,"-3425.416015625") -- PosY
table.insert(DropPointsZ,"170.56161499023") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-2011.8402099609") -- PosX
table.insert(DropPointsY,"-3075.2902832031") -- PosY
table.insert(DropPointsZ,"268.66372680664") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1991.5943603516") -- PosX
table.insert(DropPointsY,"-2701.1181640625") -- PosY
table.insert(DropPointsZ,"167.84129333496") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-2144.7592773438") -- PosX
table.insert(DropPointsY,"-1070.0173339844") -- PosY
table.insert(DropPointsZ,"132.68908691406") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1401.8494873047") -- PosX
table.insert(DropPointsY,"-391.8307800293") -- PosY
table.insert(DropPointsZ,"183.63336181641") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-329.78475952148") -- PosX
table.insert(DropPointsY,"-1932.5968017578") -- PosY
table.insert(DropPointsZ,"372.84375") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-6.5064721107483") -- PosX
table.insert(DropPointsY,"-2047.08984375") -- PosY
table.insert(DropPointsZ,"304.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-141.66937255859") -- PosX
table.insert(DropPointsY,"-2743.3142089844") -- PosY
table.insert(DropPointsZ,"364.86370849609") -- PosZ