-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"152.32116699219") -- PosX
table.insert(DropPointsY,"286.79821777344") -- PosY
table.insert(DropPointsZ,"-190.82737731934") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"245.02812194824") -- PosX
table.insert(DropPointsY,"158.21458435059") -- PosY
table.insert(DropPointsZ,"-234.7487487793") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"32.347629547119") -- PosX
table.insert(DropPointsY,"289.14297485352") -- PosY
table.insert(DropPointsZ,"-252.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-31.879739761353") -- PosX
table.insert(DropPointsY,"-38.145904541016") -- PosY
table.insert(DropPointsZ,"-252.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"117.68030548096") -- PosX
table.insert(DropPointsY,"16.642557144165") -- PosY
table.insert(DropPointsZ,"-123.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-71.435287475586") -- PosX
table.insert(DropPointsY,"-31.486707687378") -- PosY
table.insert(DropPointsZ,"-123.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"152.72143554688") -- PosX
table.insert(DropPointsY,"-91.862861633301") -- PosY
table.insert(DropPointsZ,"-93.053749084473") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-167.91012573242") -- PosX
table.insert(DropPointsY,"290.79702758789") -- PosY
table.insert(DropPointsZ,"-161.11614990234") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-690.86700439453") -- PosX
table.insert(DropPointsY,"744.93115234375") -- PosY
table.insert(DropPointsZ,"-187.47624206543") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"239.25813293457") -- PosX
table.insert(DropPointsY,"293.3583984375") -- PosY
table.insert(DropPointsZ,"-254.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"974.25823974609") -- PosX
table.insert(DropPointsY,"721.20733642578") -- PosY
table.insert(DropPointsZ,"-179.44564819336") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"720.04034423828") -- PosX
table.insert(DropPointsY,"-402.22064208984") -- PosY
table.insert(DropPointsZ,"-151.22407531738") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"922.61566162109") -- PosX
table.insert(DropPointsY,"-663.58111572266") -- PosY
table.insert(DropPointsZ,"-104.38966369629") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-721.45251464844") -- PosX
table.insert(DropPointsY,"-700.93359375") -- PosY
table.insert(DropPointsZ,"-174.89117431641") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"136.55828857422") -- PosX
table.insert(DropPointsY,"256.11712646484") -- PosY
table.insert(DropPointsZ,"1.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-14.475336074829") -- PosX
table.insert(DropPointsY,"16.278547286987") -- PosY
table.insert(DropPointsZ,"1.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-44.91918182373") -- PosX
table.insert(DropPointsY,"-89.750076293945") -- PosY
table.insert(DropPointsZ,"-249.99975585938") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"343.5514831543") -- PosX
table.insert(DropPointsY,"-221.69836425781") -- PosY
table.insert(DropPointsZ,"-212.14924621582") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"244.03125") -- PosX
table.insert(DropPointsY,"10.147685050964") -- PosY
table.insert(DropPointsZ,"-183.72319030762") -- PosZ