-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"391.40469360352") -- PosX
table.insert(DropPointsY,"-1080.8811035156") -- PosY
table.insert(DropPointsZ,"-954.67626953125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"234.83187866211") -- PosX
table.insert(DropPointsY,"-806.28668212891") -- PosY
table.insert(DropPointsZ,"-1023.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-218.56620788574") -- PosX
table.insert(DropPointsY,"-964.97961425781") -- PosY
table.insert(DropPointsZ,"-990.16491699219") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-180.78062438965") -- PosX
table.insert(DropPointsY,"-1126.8642578125") -- PosY
table.insert(DropPointsZ,"-951.10437011719") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"135.70327758789") -- PosX
table.insert(DropPointsY,"-1187.8343505859") -- PosY
table.insert(DropPointsZ,"-955.33624267578") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"201.58767700195") -- PosX
table.insert(DropPointsY,"-1284.5798339844") -- PosY
table.insert(DropPointsZ,"-1023.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"331.33325195313") -- PosX
table.insert(DropPointsY,"-1448.4173583984") -- PosY
table.insert(DropPointsZ,"-927.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"538.20684814453") -- PosX
table.insert(DropPointsY,"-1057.2580566406") -- PosY
table.insert(DropPointsZ,"-927.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"547.08233642578") -- PosX
table.insert(DropPointsY,"-403.65783691406") -- PosY
table.insert(DropPointsZ,"-927.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-623.95068359375") -- PosX
table.insert(DropPointsY,"-1012.2442626953") -- PosY
table.insert(DropPointsZ,"-927.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-39.96875") -- PosX
table.insert(DropPointsY,"-868.19537353516") -- PosY
table.insert(DropPointsZ,"-895.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-245.75968933105") -- PosX
table.insert(DropPointsY,"-805.18609619141") -- PosY
table.insert(DropPointsZ,"-895.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-249.97113037109") -- PosX
table.insert(DropPointsY,"-1125.4808349609") -- PosY
table.insert(DropPointsZ,"-895.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"37.712093353271") -- PosX
table.insert(DropPointsY,"-932.39562988281") -- PosY
table.insert(DropPointsZ,"-895.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"131.97790527344") -- PosX
table.insert(DropPointsY,"-1383.96875") -- PosY
table.insert(DropPointsZ,"-895.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"408.23782348633") -- PosX
table.insert(DropPointsY,"-807.96771240234") -- PosY
table.insert(DropPointsZ,"-767.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"417.9196472168") -- PosX
table.insert(DropPointsY,"-1105.3336181641") -- PosY
table.insert(DropPointsZ,"-767.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-143.55975341797") -- PosX
table.insert(DropPointsY,"-1117.8734130859") -- PosY
table.insert(DropPointsZ,"-767.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-154.90641784668") -- PosX
table.insert(DropPointsY,"-815.27313232422") -- PosY
table.insert(DropPointsZ,"-767.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"35.396373748779") -- PosX
table.insert(DropPointsY,"-735.88543701172") -- PosY
table.insert(DropPointsZ,"-767.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"373.91146850586") -- PosX
table.insert(DropPointsY,"-1111.8776855469") -- PosY
table.insert(DropPointsZ,"-895.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"246.134765625") -- PosX
table.insert(DropPointsY,"-1382.5031738281") -- PosY
table.insert(DropPointsZ,"-895.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"414.58609008789") -- PosX
table.insert(DropPointsY,"-845.92980957031") -- PosY
table.insert(DropPointsZ,"-1023.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-160.0099029541") -- PosX
table.insert(DropPointsY,"-1096.2233886719") -- PosY
table.insert(DropPointsZ,"-581.75860595703") -- PosZ