-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"363.8742980957") -- PosX
table.insert(DropPointsY,"-917.40789794922") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"322.3205871582") -- PosX
table.insert(DropPointsY,"-2015.8548583984") -- PosY
table.insert(DropPointsZ,"114.01287841797") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"343.49783325195") -- PosX
table.insert(DropPointsY,"-2594.5612792969") -- PosY
table.insert(DropPointsZ,"118.93997192383") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2283.1533203125") -- PosX
table.insert(DropPointsY,"-3080.1789550781") -- PosY
table.insert(DropPointsZ,"68.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2079.6669921875") -- PosX
table.insert(DropPointsY,"-3051.2209472656") -- PosY
table.insert(DropPointsZ,"145.11441040039") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1879.8934326172") -- PosX
table.insert(DropPointsY,"-2948.2915039063") -- PosY
table.insert(DropPointsZ,"142.62440490723") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2216.490234375") -- PosX
table.insert(DropPointsY,"-2762.158203125") -- PosY
table.insert(DropPointsZ,"68.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1637.1704101563") -- PosX
table.insert(DropPointsY,"-3127.2338867188") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2743.7707519531") -- PosX
table.insert(DropPointsY,"-2526.9729003906") -- PosY
table.insert(DropPointsZ,"178.25796508789") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2519.1975097656") -- PosX
table.insert(DropPointsY,"-1105.0346679688") -- PosY
table.insert(DropPointsZ,"32.562797546387") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2542.3271484375") -- PosX
table.insert(DropPointsY,"-648.66461181641") -- PosY
table.insert(DropPointsZ,"103.32356262207") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2126.9343261719") -- PosX
table.insert(DropPointsY,"-657.08935546875") -- PosY
table.insert(DropPointsZ,"146.23686218262") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1399.3596191406") -- PosX
table.insert(DropPointsY,"-535.39147949219") -- PosY
table.insert(DropPointsZ,"72.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"820.09606933594") -- PosX
table.insert(DropPointsY,"-1036.5307617188") -- PosY
table.insert(DropPointsZ,"72.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1771.166015625") -- PosX
table.insert(DropPointsY,"-850.62664794922") -- PosY
table.insert(DropPointsZ,"266.84375") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1292.7022705078") -- PosX
table.insert(DropPointsY,"-1118.166015625") -- PosY
table.insert(DropPointsZ,"127.60625457764") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1457.4822998047") -- PosX
table.insert(DropPointsY,"-1154.193359375") -- PosY
table.insert(DropPointsZ,"129.38784790039") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"937.63049316406") -- PosX
table.insert(DropPointsY,"-2213.5930175781") -- PosY
table.insert(DropPointsZ,"72.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"557.9013671875") -- PosX
table.insert(DropPointsY,"-2051.7646484375") -- PosY
table.insert(DropPointsZ,"145.1768951416") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"891.29595947266") -- PosX
table.insert(DropPointsY,"-1758.3022460938") -- PosY
table.insert(DropPointsZ,"72.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1454.4844970703") -- PosX
table.insert(DropPointsY,"-1887.5756835938") -- PosY
table.insert(DropPointsZ,"145.17692565918") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1223.6141357422") -- PosX
table.insert(DropPointsY,"-1992.5036621094") -- PosY
table.insert(DropPointsZ,"266.28890991211") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1601.8858642578") -- PosX
table.insert(DropPointsY,"-1710.4831542969") -- PosY
table.insert(DropPointsZ,"209.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1646.0170898438") -- PosX
table.insert(DropPointsY,"-2009.2469482422") -- PosY
table.insert(DropPointsZ,"209.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"695.25659179688") -- PosX
table.insert(DropPointsY,"-2295.6958007813") -- PosY
table.insert(DropPointsZ,"209.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1288.3646240234") -- PosX
table.insert(DropPointsY,"-2264.666015625") -- PosY
table.insert(DropPointsZ,"209.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1458.4119873047") -- PosX
table.insert(DropPointsY,"-2293.2182617188") -- PosY
table.insert(DropPointsZ,"273.16372680664") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1851.6942138672") -- PosX
table.insert(DropPointsY,"-1978.9266357422") -- PosY
table.insert(DropPointsZ,"203.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2008.8443603516") -- PosX
table.insert(DropPointsY,"-1710.8525390625") -- PosY
table.insert(DropPointsZ,"201.32342529297") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2011.2484130859") -- PosX
table.insert(DropPointsY,"-2221.7631835938") -- PosY
table.insert(DropPointsZ,"123.28125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"893.14227294922") -- PosX
table.insert(DropPointsY,"-3126.6430664063") -- PosY
table.insert(DropPointsZ,"72.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"354.40585327148") -- PosX
table.insert(DropPointsY,"-3164.2307128906") -- PosY
table.insert(DropPointsZ,"89.501251220703") -- PosZ