-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"335.86349487305") -- PosX
table.insert(DropPointsY,"3056.9904785156") -- PosY
table.insert(DropPointsZ,"-1089.1362304688") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"238.2204284668") -- PosX
table.insert(DropPointsY,"2927.5290527344") -- PosY
table.insert(DropPointsZ,"-954.27801513672") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"239.89111328125") -- PosX
table.insert(DropPointsY,"2543.5446777344") -- PosY
table.insert(DropPointsZ,"-1128.4362792969") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1061.3924560547") -- PosX
table.insert(DropPointsY,"2679.2802734375") -- PosY
table.insert(DropPointsZ,"-1141.5762939453") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"663.84631347656") -- PosX
table.insert(DropPointsY,"2644.7446289063") -- PosY
table.insert(DropPointsZ,"-969.19873046875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"322.12905883789") -- PosX
table.insert(DropPointsY,"2147.5961914063") -- PosY
table.insert(DropPointsZ,"-1090.5118408203") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-383.21255493164") -- PosX
table.insert(DropPointsY,"1671.009765625") -- PosY
table.insert(DropPointsZ,"-1092.4362792969") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-190.90701293945") -- PosX
table.insert(DropPointsY,"2226.8068847656") -- PosY
table.insert(DropPointsZ,"-1089.5667724609") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-526.65344238281") -- PosX
table.insert(DropPointsY,"2309.9191894531") -- PosY
table.insert(DropPointsZ,"-1149.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-761.50726318359") -- PosX
table.insert(DropPointsY,"1407.1311035156") -- PosY
table.insert(DropPointsZ,"-1165.0510253906") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-912.20251464844") -- PosX
table.insert(DropPointsY,"2023.2822265625") -- PosY
table.insert(DropPointsZ,"-1116.1529541016") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1037.2244873047") -- PosX
table.insert(DropPointsY,"1660.8006591797") -- PosY
table.insert(DropPointsZ,"-1087.6887207031") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-634.41784667969") -- PosX
table.insert(DropPointsY,"2291.8850097656") -- PosY
table.insert(DropPointsZ,"-1091.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1021.4085693359") -- PosX
table.insert(DropPointsY,"2217.806640625") -- PosY
table.insert(DropPointsZ,"-969.44897460938") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1047.3177490234") -- PosX
table.insert(DropPointsY,"2198.6491699219") -- PosY
table.insert(DropPointsZ,"-1079.8787841797") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1232.9267578125") -- PosX
table.insert(DropPointsY,"2210.1655273438") -- PosY
table.insert(DropPointsZ,"-1088.8039550781") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"597.80999755859") -- PosX
table.insert(DropPointsY,"2755.669921875") -- PosY
table.insert(DropPointsZ,"-1093.0438232422") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"697.98693847656") -- PosX
table.insert(DropPointsY,"2004.7904052734") -- PosY
table.insert(DropPointsZ,"-1080.6762695313") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1045.0239257813") -- PosX
table.insert(DropPointsY,"2324.9992675781") -- PosY
table.insert(DropPointsZ,"-1023.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1076.3189697266") -- PosX
table.insert(DropPointsY,"1943.1750488281") -- PosY
table.insert(DropPointsZ,"-1023.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"824.40295410156") -- PosX
table.insert(DropPointsY,"2439.3708496094") -- PosY
table.insert(DropPointsZ,"-997.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"381.59280395508") -- PosX
table.insert(DropPointsY,"1574.3176269531") -- PosY
table.insert(DropPointsZ,"-1095.3411865234") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-253.32830810547") -- PosX
table.insert(DropPointsY,"1426.4727783203") -- PosY
table.insert(DropPointsZ,"-1136.6463623047") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-130.73292541504") -- PosX
table.insert(DropPointsY,"1672.5250244141") -- PosY
table.insert(DropPointsZ,"-1031.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"303.29187011719") -- PosX
table.insert(DropPointsY,"1844.1584472656") -- PosY
table.insert(DropPointsZ,"-1026.71875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"524.71734619141") -- PosX
table.insert(DropPointsY,"1913.4505615234") -- PosY
table.insert(DropPointsZ,"-1008.7038574219") -- PosZ