-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"1471.2796630859") -- PosX
table.insert(DropPointsY,"1875.103515625") -- PosY
table.insert(DropPointsZ,"-274.43627929688") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1835.1251220703") -- PosX
table.insert(DropPointsY,"1789.0289306641") -- PosY
table.insert(DropPointsZ,"-263.15625") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1640.1958007813") -- PosX
table.insert(DropPointsY,"1490.8172607422") -- PosY
table.insert(DropPointsZ,"-284.49508666992") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1972.537109375") -- PosX
table.insert(DropPointsY,"1336.6824951172") -- PosY
table.insert(DropPointsZ,"-266.15628051758") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1498.7974853516") -- PosX
table.insert(DropPointsY,"1429.6124267578") -- PosY
table.insert(DropPointsZ,"-263.59875488281") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1707.8068847656") -- PosX
table.insert(DropPointsY,"1317.9283447266") -- PosY
table.insert(DropPointsZ,"-387.15698242188") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1453.6644287109") -- PosX
table.insert(DropPointsY,"1615.6209716797") -- PosY
table.insert(DropPointsZ,"-449.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1982.0882568359") -- PosX
table.insert(DropPointsY,"1860.0469970703") -- PosY
table.insert(DropPointsZ,"-381.15625") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1987.2373046875") -- PosX
table.insert(DropPointsY,"1523.3538818359") -- PosY
table.insert(DropPointsZ,"-567.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1974.6834716797") -- PosX
table.insert(DropPointsY,"1831.3636474609") -- PosY
table.insert(DropPointsZ,"-505.08874511719") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1463.7506103516") -- PosX
table.insert(DropPointsY,"1862.4537353516") -- PosY
table.insert(DropPointsZ,"-531.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1539.6612548828") -- PosX
table.insert(DropPointsY,"1054.3952636719") -- PosY
table.insert(DropPointsZ,"-566.55828857422") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1539.5054931641") -- PosX
table.insert(DropPointsY,"628.10595703125") -- PosY
table.insert(DropPointsZ,"-617.10717773438") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1364.572265625") -- PosX
table.insert(DropPointsY,"251.96873474121") -- PosY
table.insert(DropPointsZ,"-627.04876708984") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"997.31481933594") -- PosX
table.insert(DropPointsY,"-325.28204345703") -- PosY
table.insert(DropPointsZ,"-533.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1693.8676757813") -- PosX
table.insert(DropPointsY,"-354.32525634766") -- PosY
table.insert(DropPointsZ,"-533.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1400.1862792969") -- PosX
table.insert(DropPointsY,"325.12237548828") -- PosY
table.insert(DropPointsZ,"-334.83975219727") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"28.164478302002") -- PosX
table.insert(DropPointsY,"471.99395751953") -- PosY
table.insert(DropPointsZ,"-523.46014404297") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"18.363742828369") -- PosX
table.insert(DropPointsY,"1617.6007080078") -- PosY
table.insert(DropPointsZ,"-447.65176391602") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"764.68041992188") -- PosX
table.insert(DropPointsY,"1769.1783447266") -- PosY
table.insert(DropPointsZ,"-389.52722167969") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"746.49768066406") -- PosX
table.insert(DropPointsY,"1558.8713378906") -- PosY
table.insert(DropPointsZ,"-288.26281738281") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"223.53698730469") -- PosX
table.insert(DropPointsY,"1957.4505615234") -- PosY
table.insert(DropPointsZ,"-388.27627563477") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1208.7052001953") -- PosX
table.insert(DropPointsY,"1004.4278564453") -- PosY
table.insert(DropPointsZ,"-327.03207397461") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2724.8059082031") -- PosX
table.insert(DropPointsY,"771.33911132813") -- PosY
table.insert(DropPointsZ,"-392.74215698242") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2682.9526367188") -- PosX
table.insert(DropPointsY,"2206.2829589844") -- PosY
table.insert(DropPointsZ,"-366.04217529297") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2156.5705566406") -- PosX
table.insert(DropPointsY,"2780.7082519531") -- PosY
table.insert(DropPointsZ,"-443.37628173828") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1543.0484619141") -- PosX
table.insert(DropPointsY,"2359.0954589844") -- PosY
table.insert(DropPointsZ,"-394.73626708984") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1258.9235839844") -- PosX
table.insert(DropPointsY,"3002.7548828125") -- PosY
table.insert(DropPointsZ,"-406.83627319336") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1633.8736572266") -- PosX
table.insert(DropPointsY,"1512.8315429688") -- PosY
table.insert(DropPointsZ,"-398.39877319336") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1216.2545166016") -- PosX
table.insert(DropPointsY,"1624.998046875") -- PosY
table.insert(DropPointsZ,"-424.4440612793") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1474.9739990234") -- PosX
table.insert(DropPointsY,"2347.6906738281") -- PosY
table.insert(DropPointsZ,"-261.28778076172") -- PosZ