-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"3535.9020996094") -- PosX
table.insert(DropPointsY,"-2921.4916992188") -- PosY
table.insert(DropPointsZ,"-575.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3320.5270996094") -- PosX
table.insert(DropPointsY,"-2645.2985839844") -- PosY
table.insert(DropPointsZ,"-498.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2615.5883789063") -- PosX
table.insert(DropPointsY,"-2096.4501953125") -- PosY
table.insert(DropPointsZ,"-539.14398193359") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2822.7412109375") -- PosX
table.insert(DropPointsY,"-2937.0637207031") -- PosY
table.insert(DropPointsZ,"-566.88104248047") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3393.7734375") -- PosX
table.insert(DropPointsY,"-2900.15625") -- PosY
table.insert(DropPointsZ,"-490.35144042969") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2967.8073730469") -- PosX
table.insert(DropPointsY,"-2815.4106445313") -- PosY
table.insert(DropPointsZ,"-567.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2957.8395996094") -- PosX
table.insert(DropPointsY,"-2579.228515625") -- PosY
table.insert(DropPointsZ,"-567.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3019.521484375") -- PosX
table.insert(DropPointsY,"-2935.775390625") -- PosY
table.insert(DropPointsZ,"-372.4762878418") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2796.4418945313") -- PosX
table.insert(DropPointsY,"-3035.6162109375") -- PosY
table.insert(DropPointsZ,"-439.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2894.1525878906") -- PosX
table.insert(DropPointsY,"-2596.8591308594") -- PosY
table.insert(DropPointsZ,"-377.08877563477") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3142.9973144531") -- PosX
table.insert(DropPointsY,"-2793.0681152344") -- PosY
table.insert(DropPointsZ,"-370.96878051758") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3299.2727050781") -- PosX
table.insert(DropPointsY,"-2717.0930175781") -- PosY
table.insert(DropPointsZ,"-439.93682861328") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3247.5190429688") -- PosX
table.insert(DropPointsY,"-3024.8569335938") -- PosY
table.insert(DropPointsZ,"-439.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2963.6916503906") -- PosX
table.insert(DropPointsY,"-3034.0825195313") -- PosY
table.insert(DropPointsZ,"-303.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3069.7333984375") -- PosX
table.insert(DropPointsY,"-2579.984375") -- PosY
table.insert(DropPointsZ,"-303.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3128.7368164063") -- PosX
table.insert(DropPointsY,"-2589.5192871094") -- PosY
table.insert(DropPointsZ,"-567.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3127.6433105469") -- PosX
table.insert(DropPointsY,"-2208.71875") -- PosY
table.insert(DropPointsZ,"-569.31903076172") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2815.5795898438") -- PosX
table.insert(DropPointsY,"-3280.9541015625") -- PosY
table.insert(DropPointsZ,"-560.88244628906") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3311.3422851563") -- PosX
table.insert(DropPointsY,"-3125.3269042969") -- PosY
table.insert(DropPointsZ,"-453.22412109375") -- PosZ