-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"996.41052246094") -- PosX
table.insert(DropPointsY,"-206.25910949707") -- PosY
table.insert(DropPointsZ,"-798.30010986328") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1416.6302490234") -- PosX
table.insert(DropPointsY,"148.90580749512") -- PosY
table.insert(DropPointsZ,"-639.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"239.54257202148") -- PosX
table.insert(DropPointsY,"131.33302307129") -- PosY
table.insert(DropPointsZ,"-708.71875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"208.17417907715") -- PosX
table.insert(DropPointsY,"613.19818115234") -- PosY
table.insert(DropPointsZ,"-755.15484619141") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"556.85864257813") -- PosX
table.insert(DropPointsY,"1152.3038330078") -- PosY
table.insert(DropPointsZ,"-786.74731445313") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1856.6934814453") -- PosX
table.insert(DropPointsY,"540.14788818359") -- PosY
table.insert(DropPointsZ,"-819.33624267578") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1695.9838867188") -- PosX
table.insert(DropPointsY,"723.64868164063") -- PosY
table.insert(DropPointsZ,"-781.65625") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1693.8489990234") -- PosX
table.insert(DropPointsY,"223.45770263672") -- PosY
table.insert(DropPointsZ,"-893.24877929688") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1885.9443359375") -- PosX
table.insert(DropPointsY,"-237.58137512207") -- PosY
table.insert(DropPointsZ,"-899.99877929688") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1276.8243408203") -- PosX
table.insert(DropPointsY,"55.790023803711") -- PosY
table.insert(DropPointsZ,"-887.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-587.75103759766") -- PosX
table.insert(DropPointsY,"-91.696311950684") -- PosY
table.insert(DropPointsZ,"-737.197265625") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-983.45104980469") -- PosX
table.insert(DropPointsY,"371.35342407227") -- PosY
table.insert(DropPointsZ,"-495.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1071.2106933594") -- PosX
table.insert(DropPointsY,"1114.4704589844") -- PosY
table.insert(DropPointsZ,"-562.71875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-25.925497055054") -- PosX
table.insert(DropPointsY,"191.49394226074") -- PosY
table.insert(DropPointsZ,"-613.63623046875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"799.09759521484") -- PosX
table.insert(DropPointsY,"-157.89270019531") -- PosY
table.insert(DropPointsZ,"-526.67626953125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1224.5109863281") -- PosX
table.insert(DropPointsY,"792.51257324219") -- PosY
table.insert(DropPointsZ,"-828.71875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1767.6324462891") -- PosX
table.insert(DropPointsY,"81.273071289063") -- PosY
table.insert(DropPointsZ,"-771.13623046875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1476.6190185547") -- PosX
table.insert(DropPointsY,"-97.350715637207") -- PosY
table.insert(DropPointsZ,"-702.15625") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"338.48199462891") -- PosX
table.insert(DropPointsY,"37.122287750244") -- PosY
table.insert(DropPointsZ,"-539.77465820313") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-291.76251220703") -- PosX
table.insert(DropPointsY,"579.04724121094") -- PosY
table.insert(DropPointsZ,"-721.24584960938") -- PosZ