-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"847.90252685547") -- PosX
table.insert(DropPointsY,"-832.63604736328") -- PosY
table.insert(DropPointsZ,"-998.91455078125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"744.06280517578") -- PosX
table.insert(DropPointsY,"-900.83862304688") -- PosY
table.insert(DropPointsZ,"-935.32202148438") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"541.81036376953") -- PosX
table.insert(DropPointsY,"-1309.6916503906") -- PosY
table.insert(DropPointsZ,"-1082.3254394531") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-11.875728607178") -- PosX
table.insert(DropPointsY,"-1563.1655273438") -- PosY
table.insert(DropPointsZ,"-1139.8579101563") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"168.73846435547") -- PosX
table.insert(DropPointsY,"-927.45074462891") -- PosY
table.insert(DropPointsZ,"-1070.6254882813") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-206.15014648438") -- PosX
table.insert(DropPointsY,"-1130.97265625") -- PosY
table.insert(DropPointsZ,"-1195.5987548828") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-251.11953735352") -- PosX
table.insert(DropPointsY,"-1490.8935546875") -- PosY
table.insert(DropPointsZ,"-1194.736328125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1100.466796875") -- PosX
table.insert(DropPointsY,"-2016.3681640625") -- PosY
table.insert(DropPointsZ,"-1263.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-787.32513427734") -- PosX
table.insert(DropPointsY,"-1998.5643310547") -- PosY
table.insert(DropPointsZ,"-1263.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"394.14096069336") -- PosX
table.insert(DropPointsY,"-1450.4666748047") -- PosY
table.insert(DropPointsZ,"-1263.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"893.72265625") -- PosX
table.insert(DropPointsY,"-863.09704589844") -- PosY
table.insert(DropPointsZ,"-1194.736328125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"800.83453369141") -- PosX
table.insert(DropPointsY,"-491.58868408203") -- PosY
table.insert(DropPointsZ,"-1199.8364257813") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"115.33478546143") -- PosX
table.insert(DropPointsY,"-1703.3604736328") -- PosY
table.insert(DropPointsZ,"-939.59875488281") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-274.43478393555") -- PosX
table.insert(DropPointsY,"-1605.9400634766") -- PosY
table.insert(DropPointsZ,"-1007.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"925.75323486328") -- PosX
table.insert(DropPointsY,"-1438.189453125") -- PosY
table.insert(DropPointsZ,"-953.37622070313") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-196.25996398926") -- PosX
table.insert(DropPointsY,"-1696.7857666016") -- PosY
table.insert(DropPointsZ,"-715.25378417969") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-728.89404296875") -- PosX
table.insert(DropPointsY,"-1275.8331298828") -- PosY
table.insert(DropPointsZ,"-457.41204833984") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-440.64074707031") -- PosX
table.insert(DropPointsY,"145.83595275879") -- PosY
table.insert(DropPointsZ,"-421.99975585938") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-58.494037628174") -- PosX
table.insert(DropPointsY,"936.91082763672") -- PosY
table.insert(DropPointsZ,"-363.43878173828") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"474.8840637207") -- PosX
table.insert(DropPointsY,"-361.28820800781") -- PosY
table.insert(DropPointsZ,"-762.67626953125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"212.11018371582") -- PosX
table.insert(DropPointsY,"-690.60791015625") -- PosY
table.insert(DropPointsZ,"-689.68872070313") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"199.80784606934") -- PosX
table.insert(DropPointsY,"700.87060546875") -- PosY
table.insert(DropPointsZ,"-511.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"399.50122070313") -- PosX
table.insert(DropPointsY,"55.37829208374") -- PosY
table.insert(DropPointsZ,"-447.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-18.627426147461") -- PosX
table.insert(DropPointsY,"-905.33825683594") -- PosY
table.insert(DropPointsZ,"-279.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-200.21176147461") -- PosX
table.insert(DropPointsY,"-1276.3413085938") -- PosY
table.insert(DropPointsZ,"-161.98095703125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1233.8012695313") -- PosX
table.insert(DropPointsY,"-2026.6201171875") -- PosY
table.insert(DropPointsZ,"-554.05627441406") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-2078.0219726563") -- PosX
table.insert(DropPointsY,"-2029.1599121094") -- PosY
table.insert(DropPointsZ,"-447.13629150391") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1284.6629638672") -- PosX
table.insert(DropPointsY,"-1822.9626464844") -- PosY
table.insert(DropPointsZ,"-310.73626708984") -- PosZ