-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"-873.86358642578") -- PosX
table.insert(DropPointsY,"-252.49127197266") -- PosY
table.insert(DropPointsZ,"70.606254577637") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1181.2185058594") -- PosX
table.insert(DropPointsY,"-615.22412109375") -- PosY
table.insert(DropPointsZ,"259.12997436523") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1559.5356445313") -- PosX
table.insert(DropPointsY,"-312.26779174805") -- PosY
table.insert(DropPointsZ,"268.13537597656") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1572.1942138672") -- PosX
table.insert(DropPointsY,"944.74865722656") -- PosY
table.insert(DropPointsZ,"304.80120849609") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1559.2679443359") -- PosX
table.insert(DropPointsY,"-78.375831604004") -- PosY
table.insert(DropPointsZ,"96.801239013672") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1139.9243164063") -- PosX
table.insert(DropPointsY,"524.39611816406") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-440.53820800781") -- PosX
table.insert(DropPointsY,"405.68350219727") -- PosY
table.insert(DropPointsZ,"99.523742675781") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-309.44439697266") -- PosX
table.insert(DropPointsY,"1144.5915527344") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-876.72198486328") -- PosX
table.insert(DropPointsY,"1162.7286376953") -- PosY
table.insert(DropPointsZ,"99.823745727539") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1574.3992919922") -- PosX
table.insert(DropPointsY,"1257.5125732422") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-67.898635864258") -- PosX
table.insert(DropPointsY,"-136.03523254395") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-438.87850952148") -- PosX
table.insert(DropPointsY,"-865.37768554688") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-673.98492431641") -- PosX
table.insert(DropPointsY,"-443.24932861328") -- PosY
table.insert(DropPointsZ,"48.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1161.7745361328") -- PosX
table.insert(DropPointsY,"236.31655883789") -- PosY
table.insert(DropPointsZ,"107.49668884277") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"463.75909423828") -- PosX
table.insert(DropPointsY,"198.56086730957") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"931.00872802734") -- PosX
table.insert(DropPointsY,"894.26116943359") -- PosY
table.insert(DropPointsZ,"107.28124237061") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"760.52020263672") -- PosX
table.insert(DropPointsY,"1465.5489501953") -- PosY
table.insert(DropPointsZ,"70.606254577637") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"469.95895385742") -- PosX
table.insert(DropPointsY,"1049.6407470703") -- PosY
table.insert(DropPointsZ,"150.36680603027") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"124.54542541504") -- PosX
table.insert(DropPointsY,"900.20098876953") -- PosY
table.insert(DropPointsZ,"48.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"145.55467224121") -- PosX
table.insert(DropPointsY,"1460.3989257813") -- PosY
table.insert(DropPointsZ,"59.856246948242") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-878.63861083984") -- PosX
table.insert(DropPointsY,"-414.94366455078") -- PosY
table.insert(DropPointsZ,"48.03125") -- PosZ