-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"-470.2278137207") -- PosX
table.insert(DropPointsY,"57.66178894043") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-296.18383789063") -- PosX
table.insert(DropPointsY,"136.25253295898") -- PosY
table.insert(DropPointsZ,"17.795310974121") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-77.261451721191") -- PosX
table.insert(DropPointsY,"153.48057556152") -- PosY
table.insert(DropPointsZ,"-349.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-169.04275512695") -- PosX
table.insert(DropPointsY,"299.7776184082") -- PosY
table.insert(DropPointsZ,"-341.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"252.6597442627") -- PosX
table.insert(DropPointsY,"489.9616394043") -- PosY
table.insert(DropPointsZ,"-615.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"125.42626190186") -- PosX
table.insert(DropPointsY,"745.76605224609") -- PosY
table.insert(DropPointsZ,"-615.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"198.82173156738") -- PosX
table.insert(DropPointsY,"1005.3723144531") -- PosY
table.insert(DropPointsZ,"-605.98553466797") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"129.47299194336") -- PosX
table.insert(DropPointsY,"995.7529296875") -- PosY
table.insert(DropPointsZ,"-605.98297119141") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"183.94590759277") -- PosX
table.insert(DropPointsY,"1412.7889404297") -- PosY
table.insert(DropPointsZ,"-601.10357666016") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-446.36810302734") -- PosX
table.insert(DropPointsY,"985.05035400391") -- PosY
table.insert(DropPointsZ,"-615.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"100.15450286865") -- PosX
table.insert(DropPointsY,"1215.5645751953") -- PosY
table.insert(DropPointsZ,"-494.89474487305") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-469.30801391602") -- PosX
table.insert(DropPointsY,"1428.7047119141") -- PosY
table.insert(DropPointsZ,"-487.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-475.77587890625") -- PosX
table.insert(DropPointsY,"1020.0433349609") -- PosY
table.insert(DropPointsZ,"-487.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-416.20611572266") -- PosX
table.insert(DropPointsY,"955.45666503906") -- PosY
table.insert(DropPointsZ,"-447.83029174805") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"178.03840637207") -- PosX
table.insert(DropPointsY,"2196.0466308594") -- PosY
table.insert(DropPointsZ,"-615.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"434.79827880859") -- PosX
table.insert(DropPointsY,"1362.9166259766") -- PosY
table.insert(DropPointsZ,"-615.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"807.76727294922") -- PosX
table.insert(DropPointsY,"2396.5441894531") -- PosY
table.insert(DropPointsZ,"-615.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"952.91687011719") -- PosX
table.insert(DropPointsY,"1791.966796875") -- PosY
table.insert(DropPointsZ,"-615.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"591.18243408203") -- PosX
table.insert(DropPointsY,"1595.3023681641") -- PosY
table.insert(DropPointsZ,"-748.14764404297") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"605.58428955078") -- PosX
table.insert(DropPointsY,"1407.3950195313") -- PosY
table.insert(DropPointsZ,"-739.80688476563") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"658.36987304688") -- PosX
table.insert(DropPointsY,"1925.0933837891") -- PosY
table.insert(DropPointsZ,"-615.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-141.68354797363") -- PosX
table.insert(DropPointsY,"289.87063598633") -- PosY
table.insert(DropPointsZ,"-341.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-471.96844482422") -- PosX
table.insert(DropPointsY,"356.32247924805") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-484.29754638672") -- PosX
table.insert(DropPointsY,"1036.6394042969") -- PosY
table.insert(DropPointsZ,"-75.256057739258") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-232.76890563965") -- PosX
table.insert(DropPointsY,"820.44476318359") -- PosY
table.insert(DropPointsZ,"8.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-604.49981689453") -- PosX
table.insert(DropPointsY,"1378.4100341797") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-597.32623291016") -- PosX
table.insert(DropPointsY,"1618.4692382813") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"27.299737930298") -- PosX
table.insert(DropPointsY,"1631.7634277344") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-462.9616394043") -- PosX
table.insert(DropPointsY,"1322.6876220703") -- PosY
table.insert(DropPointsZ,"65.84073638916") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-46.912368774414") -- PosX
table.insert(DropPointsY,"346.50979614258") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ