-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"178.95370483398") -- PosX
table.insert(DropPointsY,"-301.68890380859") -- PosY
table.insert(DropPointsZ,"-11.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"159.08955383301") -- PosX
table.insert(DropPointsY,"69.749366760254") -- PosY
table.insert(DropPointsZ,"-11.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1043.8843994141") -- PosX
table.insert(DropPointsY,"815.18609619141") -- PosY
table.insert(DropPointsZ,"178.57327270508") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-2012.7127685547") -- PosX
table.insert(DropPointsY,"16.32160949707") -- PosY
table.insert(DropPointsZ,"152.74610900879") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-2178.9758300781") -- PosX
table.insert(DropPointsY,"-1520.8981933594") -- PosY
table.insert(DropPointsZ,"96.289482116699") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"57.109771728516") -- PosX
table.insert(DropPointsY,"-1539.3946533203") -- PosY
table.insert(DropPointsZ,"145.44612121582") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"713.57824707031") -- PosX
table.insert(DropPointsY,"-1038.1129150391") -- PosY
table.insert(DropPointsZ,"28.677965164185") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"885.69110107422") -- PosX
table.insert(DropPointsY,"226.7600402832") -- PosY
table.insert(DropPointsZ,"0.41596046090126") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2167.3212890625") -- PosX
table.insert(DropPointsY,"952.41705322266") -- PosY
table.insert(DropPointsZ,"14.396230697632") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2829.1513671875") -- PosX
table.insert(DropPointsY,"-37.754207611084") -- PosY
table.insert(DropPointsZ,"6.3658094406128") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2716.1945800781") -- PosX
table.insert(DropPointsY,"-1492.4300537109") -- PosY
table.insert(DropPointsZ,"20.525352478027") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-471.98699951172") -- PosX
table.insert(DropPointsY,"-407.96875") -- PosY
table.insert(DropPointsZ,"40.670349121094") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-302.73226928711") -- PosX
table.insert(DropPointsY,"-715.61181640625") -- PosY
table.insert(DropPointsZ,"1.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-445.95672607422") -- PosX
table.insert(DropPointsY,"-595.07348632813") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-98.241928100586") -- PosX
table.insert(DropPointsY,"15.481686592102") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"59.456233978271") -- PosX
table.insert(DropPointsY,"-296.38302612305") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-246.31245422363") -- PosX
table.insert(DropPointsY,"-284.56274414063") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-486.42620849609") -- PosX
table.insert(DropPointsY,"-421.15759277344") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-233.92030334473") -- PosX
table.insert(DropPointsY,"-665.99279785156") -- PosY
table.insert(DropPointsZ,"168.47161865234") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"205.64349365234") -- PosX
table.insert(DropPointsY,"-416.97817993164") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-107.55248260498") -- PosX
table.insert(DropPointsY,"-132.66804504395") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-392.45376586914") -- PosX
table.insert(DropPointsY,"-182.88200378418") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-431.79959106445") -- PosX
table.insert(DropPointsY,"2.3653469085693") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-666.01892089844") -- PosX
table.insert(DropPointsY,"-131.45458984375") -- PosY
table.insert(DropPointsZ,"-11.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-316.71911621094") -- PosX
table.insert(DropPointsY,"-254.6262512207") -- PosY
table.insert(DropPointsZ,"347.76062011719") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"80.225494384766") -- PosX
table.insert(DropPointsY,"-155.87071228027") -- PosY
table.insert(DropPointsZ,"325.07794189453") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-22.649551391602") -- PosX
table.insert(DropPointsY,"-651.32739257813") -- PosY
table.insert(DropPointsZ,"-31.108556747437") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"176.59712219238") -- PosX
table.insert(DropPointsY,"-461.77493286133") -- PosY
table.insert(DropPointsZ,"-71.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"75.616607666016") -- PosX
table.insert(DropPointsY,"-288.3955078125") -- PosY
table.insert(DropPointsZ,"-131.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-200.18078613281") -- PosX
table.insert(DropPointsY,"0.81657147407532") -- PosY
table.insert(DropPointsZ,"-131.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-376.17025756836") -- PosX
table.insert(DropPointsY,"-8.2852602005005") -- PosY
table.insert(DropPointsZ,"-129.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-182.29136657715") -- PosX
table.insert(DropPointsY,"-285.42596435547") -- PosY
table.insert(DropPointsZ,"-131.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-426.3225402832") -- PosX
table.insert(DropPointsY,"-678.08843994141") -- PosY
table.insert(DropPointsZ,"-131.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-479.11459350586") -- PosX
table.insert(DropPointsY,"-251.22988891602") -- PosY
table.insert(DropPointsZ,"-97.54972076416") -- PosZ