-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"154.79261779785") -- PosX
table.insert(DropPointsY,"-279.65252685547") -- PosY
table.insert(DropPointsZ,"108.91600799561") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"469.57473754883") -- PosX
table.insert(DropPointsY,"-371.75631713867") -- PosY
table.insert(DropPointsZ,"168.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"235.21798706055") -- PosX
table.insert(DropPointsY,"33.723190307617") -- PosY
table.insert(DropPointsZ,"220.76699829102") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"436.08294677734") -- PosX
table.insert(DropPointsY,"-236.24610900879") -- PosY
table.insert(DropPointsZ,"233.65780639648") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"531.40625") -- PosX
table.insert(DropPointsY,"-93.96875") -- PosY
table.insert(DropPointsZ,"83.751251220703") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"566.64465332031") -- PosX
table.insert(DropPointsY,"-330.18045043945") -- PosY
table.insert(DropPointsZ,"114.26373291016") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"443.99624633789") -- PosX
table.insert(DropPointsY,"-97.187973022461") -- PosY
table.insert(DropPointsZ,"49.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"49.597736358643") -- PosX
table.insert(DropPointsY,"-147.16062927246") -- PosY
table.insert(DropPointsZ,"48.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"52.559474945068") -- PosX
table.insert(DropPointsY,"-19.449834823608") -- PosY
table.insert(DropPointsZ,"48.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"467.96875") -- PosX
table.insert(DropPointsY,"-27.605581283569") -- PosY
table.insert(DropPointsZ,"98.618682861328") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"64.724807739258") -- PosX
table.insert(DropPointsY,"-396.34310913086") -- PosY
table.insert(DropPointsZ,"-4.9476356506348") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"60.426006317139") -- PosX
table.insert(DropPointsY,"-10.977035522461") -- PosY
table.insert(DropPointsZ,"-9.2537488937378") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"4.4042763710022") -- PosX
table.insert(DropPointsY,"145.80459594727") -- PosY
table.insert(DropPointsZ,"38.298160552979") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"176.22314453125") -- PosX
table.insert(DropPointsY,"480.29391479492") -- PosY
table.insert(DropPointsZ,"7.6372680664063") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-365.15301513672") -- PosX
table.insert(DropPointsY,"608.98468017578") -- PosY
table.insert(DropPointsZ,"-35.058235168457") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-264.93884277344") -- PosX
table.insert(DropPointsY,"953.20294189453") -- PosY
table.insert(DropPointsZ,"-41.623748779297") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-133.73333740234") -- PosX
table.insert(DropPointsY,"497.07110595703") -- PosY
table.insert(DropPointsZ,"79.281242370605") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-236.92335510254") -- PosX
table.insert(DropPointsY,"682.78942871094") -- PosY
table.insert(DropPointsZ,"160.8401184082") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-371.54580688477") -- PosX
table.insert(DropPointsY,"783.88659667969") -- PosY
table.insert(DropPointsZ,"56.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-104.05107116699") -- PosX
table.insert(DropPointsY,"562.68591308594") -- PosY
table.insert(DropPointsZ,"-71.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"377.73385620117") -- PosX
table.insert(DropPointsY,"1663.0953369141") -- PosY
table.insert(DropPointsZ,"-87.129173278809") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"943.92755126953") -- PosX
table.insert(DropPointsY,"1194.7147216797") -- PosY
table.insert(DropPointsZ,"-48.358791351318") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"696.08673095703") -- PosX
table.insert(DropPointsY,"421.9606628418") -- PosY
table.insert(DropPointsZ,"-81.628273010254") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"300.80004882813") -- PosX
table.insert(DropPointsY,"-405.84146118164") -- PosY
table.insert(DropPointsZ,"-195.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"530.41369628906") -- PosX
table.insert(DropPointsY,"-98.671989440918") -- PosY
table.insert(DropPointsZ,"-195.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"244.33660888672") -- PosX
table.insert(DropPointsY,"51.659156799316") -- PosY
table.insert(DropPointsZ,"-2.9687483310699") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"691.24053955078") -- PosX
table.insert(DropPointsY,"-155.90745544434") -- PosY
table.insert(DropPointsZ,"-76.156852722168") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"82.362037658691") -- PosX
table.insert(DropPointsY,"-496.05572509766") -- PosY
table.insert(DropPointsZ,"-8.3995018005371") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"86.146629333496") -- PosX
table.insert(DropPointsY,"334.00994873047") -- PosY
table.insert(DropPointsZ,"144.78602600098") -- PosZ