-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"-764.89440917969") -- PosX
table.insert(DropPointsY,"365.46868896484") -- PosY
table.insert(DropPointsZ,"143.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"262.419921875") -- PosX
table.insert(DropPointsY,"-145.08424377441") -- PosY
table.insert(DropPointsZ,"15.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-58.607643127441") -- PosX
table.insert(DropPointsY,"-326.38232421875") -- PosY
table.insert(DropPointsZ,"30.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-870.39703369141") -- PosX
table.insert(DropPointsY,"-81.055671691895") -- PosY
table.insert(DropPointsZ,"15.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"446.8034362793") -- PosX
table.insert(DropPointsY,"-680.62658691406") -- PosY
table.insert(DropPointsZ,"-17.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"236.72793579102") -- PosX
table.insert(DropPointsY,"-1114.7883300781") -- PosY
table.insert(DropPointsZ,"51.323753356934") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-305.03601074219") -- PosX
table.insert(DropPointsY,"-812.70892333984") -- PosY
table.insert(DropPointsZ,"71.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-164.6943359375") -- PosX
table.insert(DropPointsY,"-791.38311767578") -- PosY
table.insert(DropPointsZ,"37.577186584473") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"323.04998779297") -- PosX
table.insert(DropPointsY,"-811.70452880859") -- PosY
table.insert(DropPointsZ,"42.863750457764") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"37.422592163086") -- PosX
table.insert(DropPointsY,"-1292.8553466797") -- PosY
table.insert(DropPointsZ,"51.031257629395") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1099.228515625") -- PosX
table.insert(DropPointsY,"-1022.8997802734") -- PosY
table.insert(DropPointsZ,"16.551235198975") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-665.61651611328") -- PosX
table.insert(DropPointsY,"-1152.0543212891") -- PosY
table.insert(DropPointsZ,"50.415283203125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-538.43389892578") -- PosX
table.insert(DropPointsY,"-995.09875488281") -- PosY
table.insert(DropPointsZ,"48.263744354248") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-402.43106079102") -- PosX
table.insert(DropPointsY,"-1074.5693359375") -- PosY
table.insert(DropPointsZ,"71.263748168945") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-437.77307128906") -- PosX
table.insert(DropPointsY,"-545.50439453125") -- PosY
table.insert(DropPointsZ,"302.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1495.2502441406") -- PosX
table.insert(DropPointsY,"-718.8828125") -- PosY
table.insert(DropPointsZ,"490.91116333008") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1459.7889404297") -- PosX
table.insert(DropPointsY,"-489.80908203125") -- PosY
table.insert(DropPointsZ,"489.31121826172") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-28.487085342407") -- PosX
table.insert(DropPointsY,"-514.42279052734") -- PosY
table.insert(DropPointsZ,"367.67126464844") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-50.245098114014") -- PosX
table.insert(DropPointsY,"-1177.9139404297") -- PosY
table.insert(DropPointsZ,"363.72222900391") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"228.44261169434") -- PosX
table.insert(DropPointsY,"-1338.4792480469") -- PosY
table.insert(DropPointsZ,"349.80120849609") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"126.88569641113") -- PosX
table.insert(DropPointsY,"-1692.7166748047") -- PosY
table.insert(DropPointsZ,"355.4977722168") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"22.204057693481") -- PosX
table.insert(DropPointsY,"-1530.1635742188") -- PosY
table.insert(DropPointsZ,"367.87036132813") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"789.65924072266") -- PosX
table.insert(DropPointsY,"-2102.96875") -- PosY
table.insert(DropPointsZ,"333.86370849609") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1224.8540039063") -- PosX
table.insert(DropPointsY,"-2148.1237792969") -- PosY
table.insert(DropPointsZ,"241.94429016113") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1040.5738525391") -- PosX
table.insert(DropPointsY,"-2149.6079101563") -- PosY
table.insert(DropPointsZ,"-98.888244628906") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-303.81005859375") -- PosX
table.insert(DropPointsY,"-1419.9051513672") -- PosY
table.insert(DropPointsZ,"362.86370849609") -- PosZ