-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"-237.93301391602") -- PosX
table.insert(DropPointsY,"-92.194862365723") -- PosY
table.insert(DropPointsZ,"100.01796722412") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-285.30288696289") -- PosX
table.insert(DropPointsY,"344.26275634766") -- PosY
table.insert(DropPointsZ,"83.843742370605") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-248.05871582031") -- PosX
table.insert(DropPointsY,"280.51965332031") -- PosY
table.insert(DropPointsZ,"248.31120300293") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-490.70849609375") -- PosX
table.insert(DropPointsY,"374.96719360352") -- PosY
table.insert(DropPointsZ,"186.93035888672") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-391.21401977539") -- PosX
table.insert(DropPointsY,"853.75030517578") -- PosY
table.insert(DropPointsZ,"114.27805328369") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"493.48010253906") -- PosX
table.insert(DropPointsY,"-94.312629699707") -- PosY
table.insert(DropPointsZ,"43.885772705078") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"915.01409912109") -- PosX
table.insert(DropPointsY,"-903.68817138672") -- PosY
table.insert(DropPointsZ,"225.58355712891") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-935.48699951172") -- PosX
table.insert(DropPointsY,"-925.64929199219") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-371.60668945313") -- PosX
table.insert(DropPointsY,"286.26257324219") -- PosY
table.insert(DropPointsZ,"54.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-104.55884552002") -- PosX
table.insert(DropPointsY,"-640.02783203125") -- PosY
table.insert(DropPointsZ,"64.695739746094") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-144.78782653809") -- PosX
table.insert(DropPointsY,"-121.26691436768") -- PosY
table.insert(DropPointsZ,"56.580074310303") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-855.90631103516") -- PosX
table.insert(DropPointsY,"-820.60406494141") -- PosY
table.insert(DropPointsZ,"93.833702087402") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-655.72607421875") -- PosX
table.insert(DropPointsY,"-804.07147216797") -- PosY
table.insert(DropPointsZ,"192.94326782227") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-277.48608398438") -- PosX
table.insert(DropPointsY,"-72.443031311035") -- PosY
table.insert(DropPointsZ,"244.33558654785") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-390.21978759766") -- PosX
table.insert(DropPointsY,"32.064548492432") -- PosY
table.insert(DropPointsZ,"213.28125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-503.48028564453") -- PosX
table.insert(DropPointsY,"-94.235748291016") -- PosY
table.insert(DropPointsZ,"117.72314453125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-740.04510498047") -- PosX
table.insert(DropPointsY,"646.43310546875") -- PosY
table.insert(DropPointsZ,"-73.206268310547") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"754.58447265625") -- PosX
table.insert(DropPointsY,"756.00982666016") -- PosY
table.insert(DropPointsZ,"-22.336664199829") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"99.996437072754") -- PosX
table.insert(DropPointsY,"-593.43298339844") -- PosY
table.insert(DropPointsZ,"51.501358032227") -- PosZ