-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"175.71557617188") -- PosX
table.insert(DropPointsY,"-214.16806030273") -- PosY
table.insert(DropPointsZ,"64.163749694824") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"291.87554931641") -- PosX
table.insert(DropPointsY,"168.15815734863") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"43.898540496826") -- PosX
table.insert(DropPointsY,"-472.94381713867") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"71.452926635742") -- PosX
table.insert(DropPointsY,"146.87069702148") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-278.27252197266") -- PosX
table.insert(DropPointsY,"46.798557281494") -- PosY
table.insert(DropPointsZ,"-191.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"68.090263366699") -- PosX
table.insert(DropPointsY,"38.434215545654") -- PosY
table.insert(DropPointsZ,"-157.95956420898") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"167.24887084961") -- PosX
table.insert(DropPointsY,"-360.68884277344") -- PosY
table.insert(DropPointsZ,"-131.65145874023") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"176.6091003418") -- PosX
table.insert(DropPointsY,"-991.85070800781") -- PosY
table.insert(DropPointsZ,"-190.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-138.07849121094") -- PosX
table.insert(DropPointsY,"-54.654296875") -- PosY
table.insert(DropPointsZ,"257.28121948242") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"278.91873168945") -- PosX
table.insert(DropPointsY,"156.17050170898") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"44.263324737549") -- PosX
table.insert(DropPointsY,"-366.09002685547") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"78.396644592285") -- PosX
table.insert(DropPointsY,"13.356589317322") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-281.05151367188") -- PosX
table.insert(DropPointsY,"-161.84736633301") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-49.494915008545") -- PosX
table.insert(DropPointsY,"-216.03125") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-5.8758540153503") -- PosX
table.insert(DropPointsY,"-7.9630451202393") -- PosY
table.insert(DropPointsZ,"608.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"65.122032165527") -- PosX
table.insert(DropPointsY,"12.42803478241") -- PosY
table.insert(DropPointsZ,"450.26373291016") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"269.7048034668") -- PosX
table.insert(DropPointsY,"-461.6669921875") -- PosY
table.insert(DropPointsZ,"384.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"355.03625488281") -- PosX
table.insert(DropPointsY,"-465.46426391602") -- PosY
table.insert(DropPointsZ,"216.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"100.28131103516") -- PosX
table.insert(DropPointsY,"220.15983581543") -- PosY
table.insert(DropPointsZ,"216.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-347.15539550781") -- PosX
table.insert(DropPointsY,"-29.587875366211") -- PosY
table.insert(DropPointsZ,"216.03125") -- PosZ