-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"-123.96875") -- PosX
table.insert(DropPointsY,"147.84422302246") -- PosY
table.insert(DropPointsZ,"160.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-325.42431640625") -- PosX
table.insert(DropPointsY,"192.95606994629") -- PosY
table.insert(DropPointsZ,"160.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-77.632232666016") -- PosX
table.insert(DropPointsY,"-91.930877685547") -- PosY
table.insert(DropPointsZ,"160.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"168.02995300293") -- PosX
table.insert(DropPointsY,"-92.913467407227") -- PosY
table.insert(DropPointsZ,"160.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"25.161010742188") -- PosX
table.insert(DropPointsY,"35.739700317383") -- PosY
table.insert(DropPointsZ,"292.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-187.98776245117") -- PosX
table.insert(DropPointsY,"376.7805480957") -- PosY
table.insert(DropPointsZ,"292.44787597656") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"109.34600067139") -- PosX
table.insert(DropPointsY,"343.85427856445") -- PosY
table.insert(DropPointsZ,"292.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"199.29988098145") -- PosX
table.insert(DropPointsY,"6.8404598236084") -- PosY
table.insert(DropPointsZ,"197.14178466797") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-372.24349975586") -- PosX
table.insert(DropPointsY,"325.74087524414") -- PosY
table.insert(DropPointsZ,"160.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"157.39697265625") -- PosX
table.insert(DropPointsY,"265.96875") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"106.13124084473") -- PosX
table.insert(DropPointsY,"-90.363655090332") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-34.70817565918") -- PosX
table.insert(DropPointsY,"-102.33180999756") -- PosY
table.insert(DropPointsZ,"-127.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-143.00471496582") -- PosX
table.insert(DropPointsY,"260.20196533203") -- PosY
table.insert(DropPointsZ,"-127.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-14.870146751404") -- PosX
table.insert(DropPointsY,"-123.54873657227") -- PosY
table.insert(DropPointsZ,"72.529449462891") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-157.6949005127") -- PosX
table.insert(DropPointsY,"-139.96875") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-385.21478271484") -- PosX
table.insert(DropPointsY,"26.355991363525") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-372.59625244141") -- PosX
table.insert(DropPointsY,"233.25894165039") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-454.11676025391") -- PosX
table.insert(DropPointsY,"459.84622192383") -- PosY
table.insert(DropPointsZ,"28.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"42.816890716553") -- PosX
table.insert(DropPointsY,"499.54904174805") -- PosY
table.insert(DropPointsZ,"77.246864318848") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1046.3221435547") -- PosX
table.insert(DropPointsY,"1067.4495849609") -- PosY
table.insert(DropPointsZ,"0.0018386840820313") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-877.0888671875") -- PosX
table.insert(DropPointsY,"792.89453125") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-737.00518798828") -- PosX
table.insert(DropPointsY,"827.54821777344") -- PosY
table.insert(DropPointsZ,"0.0018386840820313") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-872.17779541016") -- PosX
table.insert(DropPointsY,"1053.8449707031") -- PosY
table.insert(DropPointsZ,"128.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1440.2362060547") -- PosX
table.insert(DropPointsY,"1450.2103271484") -- PosY
table.insert(DropPointsZ,"0.018211364746094") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1005.0142211914") -- PosX
table.insert(DropPointsY,"663.93530273438") -- PosY
table.insert(DropPointsZ,"122.39699554443") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1472.4044189453") -- PosX
table.insert(DropPointsY,"-1454.2160644531") -- PosY
table.insert(DropPointsZ,"0.023097991943359") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"969.74645996094") -- PosX
table.insert(DropPointsY,"-1413.5192871094") -- PosY
table.insert(DropPointsZ,"0.026878356933594") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1125.5609130859") -- PosX
table.insert(DropPointsY,"-1301.5064697266") -- PosY
table.insert(DropPointsZ,"143.17788696289") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1506.5263671875") -- PosX
table.insert(DropPointsY,"-1501.2543945313") -- PosY
table.insert(DropPointsZ,"-0.73637390136719") -- PosZ



-- Added by Deluvas
table.insert(DropPointsX,"1452.1912841797") -- PosX
table.insert(DropPointsY,"294.68923950195") -- PosY
table.insert(DropPointsZ,"106.26762390137") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1293.6662597656") -- PosX
table.insert(DropPointsY,"1322.0858154297") -- PosY
table.insert(DropPointsZ,"126.55312347412") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"251.86317443848") -- PosX
table.insert(DropPointsY,"164.05491638184") -- PosY
table.insert(DropPointsZ,"32.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-438.57159423828") -- PosX
table.insert(DropPointsY,"1351.46875") -- PosY
table.insert(DropPointsZ,"73.689735412598") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-771.65728759766") -- PosX
table.insert(DropPointsY,"988.30334472656") -- PosY
table.insert(DropPointsZ,"344.78106689453") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"84.35669708252") -- PosX
table.insert(DropPointsY,"69.588272094727") -- PosY
table.insert(DropPointsZ,"369.19857788086") -- PosZ