-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"1413.7164306641") -- PosX
table.insert(DropPointsY,"1157.3311767578") -- PosY
table.insert(DropPointsZ,"200.29753112793") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1903.9527587891") -- PosX
table.insert(DropPointsY,"1339.4541015625") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1530.7897949219") -- PosX
table.insert(DropPointsY,"900.28900146484") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"909.10540771484") -- PosX
table.insert(DropPointsY,"893.41955566406") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1343.0471191406") -- PosX
table.insert(DropPointsY,"1344.4901123047") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2000.03125") -- PosX
table.insert(DropPointsY,"1181.1257324219") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1494.6022949219") -- PosX
table.insert(DropPointsY,"1235.8303222656") -- PosY
table.insert(DropPointsZ,"-120.89836120605") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1692.8193359375") -- PosX
table.insert(DropPointsY,"946.90051269531") -- PosY
table.insert(DropPointsZ,"-159.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1348.4377441406") -- PosX
table.insert(DropPointsY,"926.01013183594") -- PosY
table.insert(DropPointsZ,"-113.96703338623") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1359.96875") -- PosX
table.insert(DropPointsY,"1359.96875") -- PosY
table.insert(DropPointsZ,"-159.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1458.1130371094") -- PosX
table.insert(DropPointsY,"1485.923828125") -- PosY
table.insert(DropPointsZ,"-159.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1438.4207763672") -- PosX
table.insert(DropPointsY,"2015.8391113281") -- PosY
table.insert(DropPointsZ,"-159.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1698.5174560547") -- PosX
table.insert(DropPointsY,"2033.4143066406") -- PosY
table.insert(DropPointsZ,"-100.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1848.9428710938") -- PosX
table.insert(DropPointsY,"1792.3315429688") -- PosY
table.insert(DropPointsZ,"-104.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1187.3360595703") -- PosX
table.insert(DropPointsY,"1678.455078125") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1221.0412597656") -- PosX
table.insert(DropPointsY,"1500.9443359375") -- PosY
table.insert(DropPointsZ,"63.08275604248") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1090.6107177734") -- PosX
table.insert(DropPointsY,"1851.8421630859") -- PosY
table.insert(DropPointsZ,"7.5667753219604") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1317.3706054688") -- PosX
table.insert(DropPointsY,"2404.8662109375") -- PosY
table.insert(DropPointsZ,"18.997659683228") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"428.06484985352") -- PosX
table.insert(DropPointsY,"1268.3200683594") -- PosY
table.insert(DropPointsZ,"16.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"424.13452148438") -- PosX
table.insert(DropPointsY,"1126.3659667969") -- PosY
table.insert(DropPointsZ,"-639.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"973.29162597656") -- PosX
table.insert(DropPointsY,"966.37677001953") -- PosY
table.insert(DropPointsZ,"-703.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1271.2072753906") -- PosX
table.insert(DropPointsY,"1105.1821289063") -- PosY
table.insert(DropPointsZ,"-703.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1140.3524169922") -- PosX
table.insert(DropPointsY,"1243.7608642578") -- PosY
table.insert(DropPointsZ,"-703.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"95.138793945313") -- PosX
table.insert(DropPointsY,"1309.4874267578") -- PosY
table.insert(DropPointsZ,"16.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"87.79761505127") -- PosX
table.insert(DropPointsY,"2603.0939941406") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"177.87596130371") -- PosX
table.insert(DropPointsY,"2404.5900878906") -- PosY
table.insert(DropPointsZ,"496.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"251.76850891113") -- PosX
table.insert(DropPointsY,"2395.9768066406") -- PosY
table.insert(DropPointsZ,"496.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2093.1423339844") -- PosX
table.insert(DropPointsY,"513.72705078125") -- PosY
table.insert(DropPointsZ,"31.170349121094") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2393.6223144531") -- PosX
table.insert(DropPointsY,"435.53115844727") -- PosY
table.insert(DropPointsZ,"496.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2277.6069335938") -- PosX
table.insert(DropPointsY,"1213.4008789063") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2000.5013427734") -- PosX
table.insert(DropPointsY,"1038.6927490234") -- PosY
table.insert(DropPointsZ,"160.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1419.8111572266") -- PosX
table.insert(DropPointsY,"1455.7900390625") -- PosY
table.insert(DropPointsZ,"200.48997497559") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"892.17443847656") -- PosX
table.insert(DropPointsY,"1539.7724609375") -- PosY
table.insert(DropPointsZ,"160.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2485.7292480469") -- PosX
table.insert(DropPointsY,"142.29585266113") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ