-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"1424.8646240234") -- PosX
table.insert(DropPointsY,"-1310.9880371094") -- PosY
table.insert(DropPointsZ,"36.520610809326") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1718.6611328125") -- PosX
table.insert(DropPointsY,"-1149.5070800781") -- PosY
table.insert(DropPointsZ,"72.852508544922") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1854.2631835938") -- PosX
table.insert(DropPointsY,"-1442.9953613281") -- PosY
table.insert(DropPointsZ,"50.343757629395") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1967.2729492188") -- PosX
table.insert(DropPointsY,"-1191.1644287109") -- PosY
table.insert(DropPointsZ,"-15.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2088.2397460938") -- PosX
table.insert(DropPointsY,"-1496.2918701172") -- PosY
table.insert(DropPointsZ,"-15.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2521.2844238281") -- PosX
table.insert(DropPointsY,"-836.62878417969") -- PosY
table.insert(DropPointsZ,"-15.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2936.5151367188") -- PosX
table.insert(DropPointsY,"-1225.0560302734") -- PosY
table.insert(DropPointsZ,"43.343757629395") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3029.1149902344") -- PosX
table.insert(DropPointsY,"-1092.5589599609") -- PosY
table.insert(DropPointsZ,"44.0012550354") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2883.4172363281") -- PosX
table.insert(DropPointsY,"-1490.6805419922") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3134.4985351563") -- PosX
table.insert(DropPointsY,"-1481.1715087891") -- PosY
table.insert(DropPointsZ,"60.863758087158") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3392.080078125") -- PosX
table.insert(DropPointsY,"-2036.1475830078") -- PosY
table.insert(DropPointsZ,"-4.7507176399231") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2262.5427246094") -- PosX
table.insert(DropPointsY,"-2039.6616210938") -- PosY
table.insert(DropPointsZ,"-7.441065788269") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2993.5393066406") -- PosX
table.insert(DropPointsY,"-2443.6472167969") -- PosY
table.insert(DropPointsZ,"107.27463531494") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"2132.490234375") -- PosX
table.insert(DropPointsY,"-2468.783203125") -- PosY
table.insert(DropPointsZ,"90.988212585449") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"3040.0688476563") -- PosX
table.insert(DropPointsY,"-3274.1408691406") -- PosY
table.insert(DropPointsZ,"50.388561248779") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1769.2137451172") -- PosX
table.insert(DropPointsY,"-2803.3146972656") -- PosY
table.insert(DropPointsZ,"-7.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1442.4519042969") -- PosX
table.insert(DropPointsY,"-2505.4953613281") -- PosY
table.insert(DropPointsZ,"42.308784484863") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"724.09954833984") -- PosX
table.insert(DropPointsY,"-2747.2333984375") -- PosY
table.insert(DropPointsZ,"-103.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1206.7783203125") -- PosX
table.insert(DropPointsY,"-2591.5808105469") -- PosY
table.insert(DropPointsZ,"-103.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1298.2165527344") -- PosX
table.insert(DropPointsY,"-2027.9676513672") -- PosY
table.insert(DropPointsZ,"-103.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1984.7749023438") -- PosX
table.insert(DropPointsY,"-1224.8078613281") -- PosY
table.insert(DropPointsZ,"124.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"562.35229492188") -- PosX
table.insert(DropPointsY,"-1576.9262695313") -- PosY
table.insert(DropPointsZ,"0.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"979.48742675781") -- PosX
table.insert(DropPointsY,"-2275.5234375") -- PosY
table.insert(DropPointsZ,"66.751251220703") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"592.45806884766") -- PosX
table.insert(DropPointsY,"-2262.5275878906") -- PosY
table.insert(DropPointsZ,"17.700613021851") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"580.28961181641") -- PosX
table.insert(DropPointsY,"-1983.20703125") -- PosY
table.insert(DropPointsZ,"197.36125183105") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"726.47180175781") -- PosX
table.insert(DropPointsY,"-2169.2587890625") -- PosY
table.insert(DropPointsZ,"195.82374572754") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"997.96875") -- PosX
table.insert(DropPointsY,"-1981.5985107422") -- PosY
table.insert(DropPointsZ,"181.72375488281") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1681.9674072266") -- PosX
table.insert(DropPointsY,"-864.06701660156") -- PosY
table.insert(DropPointsZ,"60.269187927246") -- PosZ