-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"343.96875") -- PosX
table.insert(DropPointsY,"761.40802001953") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"343.96875") -- PosX
table.insert(DropPointsY,"306.57479858398") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"336.92013549805") -- PosX
table.insert(DropPointsY,"392.18795776367") -- PosY
table.insert(DropPointsZ,"111.07804870605") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"190.87124633789") -- PosX
table.insert(DropPointsY,"463.21640014648") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"27.7952709198") -- PosX
table.insert(DropPointsY,"475.96875") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-124.66130828857") -- PosX
table.insert(DropPointsY,"288.03125") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-111.03782653809") -- PosX
table.insert(DropPointsY,"475.96875") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-127.96875") -- PosX
table.insert(DropPointsY,"516.03125") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-119.42598724365") -- PosX
table.insert(DropPointsY,"622.22778320313") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-94.427925109863") -- PosX
table.insert(DropPointsY,"767.96875") -- PosY
table.insert(DropPointsZ,"91.82054901123") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"139.96875") -- PosX
table.insert(DropPointsY,"294.03125") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-255.96875") -- PosX
table.insert(DropPointsY,"520.03125") -- PosY
table.insert(DropPointsZ,"-175.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-509.26370239258") -- PosX
table.insert(DropPointsY,"563.69970703125") -- PosY
table.insert(DropPointsZ,"-175.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-408.45660400391") -- PosX
table.insert(DropPointsY,"374.58444213867") -- PosY
table.insert(DropPointsZ,"-110.32692718506") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-309.9235534668") -- PosX
table.insert(DropPointsY,"304.16900634766") -- PosY
table.insert(DropPointsZ,"-175.96875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-412.89895629883") -- PosX
table.insert(DropPointsY,"-187.37292480469") -- PosY
table.insert(DropPointsZ,"-26.278602600098") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-686.27215576172") -- PosX
table.insert(DropPointsY,"-327.40905761719") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-644.14685058594") -- PosX
table.insert(DropPointsY,"51.432823181152") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-598.74755859375") -- PosX
table.insert(DropPointsY,"640.29614257813") -- PosY
table.insert(DropPointsZ,"176.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-477.40155029297") -- PosX
table.insert(DropPointsY,"798.97711181641") -- PosY
table.insert(DropPointsZ,"176.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"21.058912277222") -- PosX
table.insert(DropPointsY,"838.51031494141") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"420.41558837891") -- PosX
table.insert(DropPointsY,"827.22985839844") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"459.43832397461") -- PosX
table.insert(DropPointsY,"402.9895324707") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"237.89744567871") -- PosX
table.insert(DropPointsY,"598.90637207031") -- PosY
table.insert(DropPointsZ,"270.51345825195") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-576.50457763672") -- PosX
table.insert(DropPointsY,"771.15942382813") -- PosY
table.insert(DropPointsZ,"104.4923248291") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-604.62554931641") -- PosX
table.insert(DropPointsY,"545.19848632813") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"543.73681640625") -- PosX
table.insert(DropPointsY,"901.51312255859") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ