-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"347.50036621094") -- PosX
table.insert(DropPointsY,"-1118.6944580078") -- PosY
table.insert(DropPointsZ,"452.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-625.46783447266") -- PosX
table.insert(DropPointsY,"-289.80014038086") -- PosY
table.insert(DropPointsZ,"452.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-767.34204101563") -- PosX
table.insert(DropPointsY,"-573.78118896484") -- PosY
table.insert(DropPointsZ,"468.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-453.11761474609") -- PosX
table.insert(DropPointsY,"-5.3858709335327") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-411.5817565918") -- PosX
table.insert(DropPointsY,"634.44683837891") -- PosY
table.insert(DropPointsZ,"253.52372741699") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-168.4208984375") -- PosX
table.insert(DropPointsY,"375.791015625") -- PosY
table.insert(DropPointsZ,"259.37759399414") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-287.48895263672") -- PosX
table.insert(DropPointsY,"389.18392944336") -- PosY
table.insert(DropPointsZ,"248.19372558594") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-255.78210449219") -- PosX
table.insert(DropPointsY,"197.7735748291") -- PosY
table.insert(DropPointsZ,"260.66372680664") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"371.85885620117") -- PosX
table.insert(DropPointsY,"212.80200195313") -- PosY
table.insert(DropPointsZ,"232.42498779297") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"841.84399414063") -- PosX
table.insert(DropPointsY,"77.465476989746") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"983.09710693359") -- PosX
table.insert(DropPointsY,"485.72192382813") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"982.4404296875") -- PosX
table.insert(DropPointsY,"-56.594676971436") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"466.00988769531") -- PosX
table.insert(DropPointsY,"224.4832611084") -- PosY
table.insert(DropPointsZ,"336.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"479.8678894043") -- PosX
table.insert(DropPointsY,"347.34173583984") -- PosY
table.insert(DropPointsZ,"403.82373046875") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"943.89825439453") -- PosX
table.insert(DropPointsY,"476.89605712891") -- PosY
table.insert(DropPointsZ,"336.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"391.05960083008") -- PosX
table.insert(DropPointsY,"374.71243286133") -- PosY
table.insert(DropPointsZ,"406.27639770508") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"18.239803314209") -- PosX
table.insert(DropPointsY,"400.29089355469") -- PosY
table.insert(DropPointsZ,"462.66467285156") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-135.64706420898") -- PosX
table.insert(DropPointsY,"380.95526123047") -- PosY
table.insert(DropPointsZ,"347.8903503418") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-293.90237426758") -- PosX
table.insert(DropPointsY,"403.78579711914") -- PosY
table.insert(DropPointsZ,"365.43338012695") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"866.87518310547") -- PosX
table.insert(DropPointsY,"328.70288085938") -- PosY
table.insert(DropPointsZ,"480.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-173.30390930176") -- PosX
table.insert(DropPointsY,"123.46811676025") -- PosY
table.insert(DropPointsZ,"584.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-785.32965087891") -- PosX
table.insert(DropPointsY,"275.22183227539") -- PosY
table.insert(DropPointsZ,"270.25051879883") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-870.50616455078") -- PosX
table.insert(DropPointsY,"-373.36679077148") -- PosY
table.insert(DropPointsZ,"229.67120361328") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1372.2855224609") -- PosX
table.insert(DropPointsY,"791.84881591797") -- PosY
table.insert(DropPointsZ,"184.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-1146.8665771484") -- PosX
table.insert(DropPointsY,"720.77593994141") -- PosY
table.insert(DropPointsZ,"184.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1001.6219482422") -- PosX
table.insert(DropPointsY,"-742.63562011719") -- PosY
table.insert(DropPointsZ,"192.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"190.37319946289") -- PosX
table.insert(DropPointsY,"-178.05448913574") -- PosY
table.insert(DropPointsZ,"132.68428039551") -- PosZ