-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Ywa
table.Add(DropPointsX,"1609.8900146484") -- PosX
table.Add(DropPointsY,"-456.67416381836") -- PosY
table.Add(DropPointsZ,"-88.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"935.94354248047") -- PosX
table.Add(DropPointsY,"173.51182556152") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"932.21868896484") -- PosX
table.Add(DropPointsY,"-460.41540527344") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"536.79016113281") -- PosX
table.Add(DropPointsY,"-65.481986999512") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"540.57623291016") -- PosX
table.Add(DropPointsY,"-208.83108520508") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"-742.27941894531") -- PosX
table.Add(DropPointsY,"110.86288452148") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"-726.97613525391") -- PosX
table.Add(DropPointsY,"406.82632446289") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"-802.34973144531") -- PosX
table.Add(DropPointsY,"411.44445800781") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"-1215.1405029297") -- PosX
table.Add(DropPointsY,"393.43695068359") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"-1508.7481689453") -- PosX
table.Add(DropPointsY,"771.53002929688") -- PosY
table.Add(DropPointsZ,"-82.79899597168") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"-507.23745727539") -- PosX
table.Add(DropPointsY,"816.19097900391") -- PosY
table.Add(DropPointsZ,"71.716896057129") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"-223.42811584473") -- PosX
table.Add(DropPointsY,"729.17687988281") -- PosY
table.Add(DropPointsZ,"312.03125") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"-221.22535705566") -- PosX
table.Add(DropPointsY,"691.44921875") -- PosY
table.Add(DropPointsZ,"312.03125") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"-344.94125366211") -- PosX
table.Add(DropPointsY,"441.49215698242") -- PosY
table.Add(DropPointsZ,"-71.110557556152") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"95.682754516602") -- PosX
table.Add(DropPointsY,"459.25509643555") -- PosY
table.Add(DropPointsZ,"-66.176368713379") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"102.77151489258") -- PosX
table.Add(DropPointsY,"-73.533279418945") -- PosY
table.Add(DropPointsZ,"-211.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"38.012397766113") -- PosX
table.Add(DropPointsY,"-138.71328735352") -- PosY
table.Add(DropPointsZ,"-211.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"1319.7380371094") -- PosX
table.Add(DropPointsY,"391.92132568359") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"1099.5456542969") -- PosX
table.Add(DropPointsY,"429.82037353516") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"869.20581054688") -- PosX
table.Add(DropPointsY,"383.38128662109") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"764.22930908203") -- PosX
table.Add(DropPointsY,"349.95843505859") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"475.03631591797") -- PosX
table.Add(DropPointsY,"693.35009765625") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"474.88659667969") -- PosX
table.Add(DropPointsY,"643.21716308594") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"569.498046875") -- PosX
table.Add(DropPointsY,"692.83026123047") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"872.80358886719") -- PosX
table.Add(DropPointsY,"582.57135009766") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"1126.0196533203") -- PosX
table.Add(DropPointsY,"709.619140625") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"-652.8818359375") -- PosX
table.Add(DropPointsY,"-65.249702453613") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ

-- Added by Ywa
table.Add(DropPointsX,"-653.28747558594") -- PosX
table.Add(DropPointsY,"-209.71560668945") -- PosY
table.Add(DropPointsZ,"-59.96875") -- PosZ