-- File generated by the Mr. Green ZS location saver
-- www.left4green.com - www.mr-green.nl

-- Added by Deluvas
table.insert(DropPointsX,"1363.3872070313") -- PosX
table.insert(DropPointsY,"705.01257324219") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"772.41271972656") -- PosX
table.insert(DropPointsY,"916.82977294922") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"359.64300537109") -- PosX
table.insert(DropPointsY,"970.32733154297") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"383.33837890625") -- PosX
table.insert(DropPointsY,"1633.8957519531") -- PosY
table.insert(DropPointsZ,"174.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"4.4423489570618") -- PosX
table.insert(DropPointsY,"1463.3773193359") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"239.26290893555") -- PosX
table.insert(DropPointsY,"1314.4946289063") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-0.72706317901611") -- PosX
table.insert(DropPointsY,"1323.1202392578") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"233.45335388184") -- PosX
table.insert(DropPointsY,"1060.8591308594") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"825.22222900391") -- PosX
table.insert(DropPointsY,"695.56420898438") -- PosY
table.insert(DropPointsZ,"65.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"847.13330078125") -- PosX
table.insert(DropPointsY,"772.82562255859") -- PosY
table.insert(DropPointsZ,"175.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-427.79949951172") -- PosX
table.insert(DropPointsY,"697.06115722656") -- PosY
table.insert(DropPointsZ,"65.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"57.297714233398") -- PosX
table.insert(DropPointsY,"1595.2658691406") -- PosY
table.insert(DropPointsZ,"117.83410644531") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"69.71028137207") -- PosX
table.insert(DropPointsY,"2348.1843261719") -- PosY
table.insert(DropPointsZ,"174.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"-420.56384277344") -- PosX
table.insert(DropPointsY,"2490.4001464844") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"87.307479858398") -- PosX
table.insert(DropPointsY,"2400.6252441406") -- PosY
table.insert(DropPointsZ,"65.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1361.0933837891") -- PosX
table.insert(DropPointsY,"2500.2006835938") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1124.9230957031") -- PosX
table.insert(DropPointsY,"1607.1831054688") -- PosY
table.insert(DropPointsZ,"56.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"697.14532470703") -- PosX
table.insert(DropPointsY,"1574.1206054688") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"155.11405944824") -- PosX
table.insert(DropPointsY,"2387.5471191406") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"172.53207397461") -- PosX
table.insert(DropPointsY,"2304.38671875") -- PosY
table.insert(DropPointsZ,"174.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"460.08880615234") -- PosX
table.insert(DropPointsY,"2388.5275878906") -- PosY
table.insert(DropPointsZ,"197.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"544.90704345703") -- PosX
table.insert(DropPointsY,"2015.0867919922") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"398.48870849609") -- PosX
table.insert(DropPointsY,"2352.0173339844") -- PosY
table.insert(DropPointsZ,"313.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"559.56787109375") -- PosX
table.insert(DropPointsY,"2052.9760742188") -- PosY
table.insert(DropPointsZ,"313.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"1086.2772216797") -- PosX
table.insert(DropPointsY,"1162.1883544922") -- PosY
table.insert(DropPointsZ,"158.10018920898") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"848.65600585938") -- PosX
table.insert(DropPointsY,"2382.8186035156") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ

-- Added by Deluvas
table.insert(DropPointsX,"349.77569580078") -- PosX
table.insert(DropPointsY,"1952.3913574219") -- PosY
table.insert(DropPointsZ,"64.03125") -- PosZ