-- File generated by the Mr. Green ZS Automatic Spawn Generation Mechanism by Deluvas, edited by NECROSSIN
-- www.left4green.com - www.mr-green.nl
 SpawnPoints = {}
table.insert ( SpawnPoints, { Vector(1453.9656982422,763.17248535156,-111.96875), Angle(11.269816398621,166.67713928223,0) } ) 
table.insert ( SpawnPoints, { Vector(1393.9353027344,858.11962890625,-111.96875), Angle(0.10708516836166,177.7606048584,0) } ) 
table.insert ( SpawnPoints, { Vector(1378.5314941406,988.57507324219,-111.96875), Angle(0.58360534906387,179.19432067871,0) } ) 
table.insert ( SpawnPoints, { Vector(1480.0590820313,940.01678466797,-111.96875), Angle(16.009546279907,-162.17163085938,0) } ) 
table.insert ( SpawnPoints, { Vector(1323.2740478516,892.00317382813,-111.96875), Angle(16.212308883667,-162.28573608398,0) } ) 
table.insert ( SpawnPoints, { Vector(1341.7263183594,777.05358886719,-111.96875), Angle(-3.7757411003113,177.82643127441,0) } ) 
table.insert ( SpawnPoints, { Vector(1306.8992919922,1024.7474365234,-77.13606262207), Angle(3.109299659729,-150.50608825684,0) } ) 
