-- File generated by the Mr. Green ZS Automatic Spawn Generation Mechanism by Deluvas, edited by NECROSSIN
-- www.left4green.com - www.mr-green.nl
 SpawnPoints = {}
table.insert ( SpawnPoints, { Vector(-322.31851196289,-1664.0841064453,520.03125), Angle(9.0304594039917,79.641448974609,0) } ) 
table.insert ( SpawnPoints, { Vector(-326.89636230469,-1584.9378662109,520.03125), Angle(1.8004803657532,16.171264648438,0) } ) 
table.insert ( SpawnPoints, { Vector(-229.77346801758,-1582.8836669922,520.03125), Angle(3.1574714183807,39.51163482666,0) } ) 
table.insert ( SpawnPoints, { Vector(-244.35028076172,-1676.1904296875,520.03125), Angle(5.8806262016296,62.787929534912,0) } ) 
table.insert ( SpawnPoints, { Vector(-275.83908081055,-1615.1027832031,520.03125), Angle(4.2603931427002,81.520126342773,0) } ) 
table.insert ( SpawnPoints, { Vector(-366.55523681641,-1706.4735107422,520.03125), Angle(-0.60905158519745,72.308464050293,0) } ) 
table.insert ( SpawnPoints, { Vector(-273.34582519531,-1692.8360595703,389.03125), Angle(5.289439201355,89.942886352539,0) } ) 
table.insert ( SpawnPoints, { Vector(-273.65542602539,-1620.3819580078,389.03125), Angle(5.6934604644775,90.155242919922,0) } ) 
table.insert ( SpawnPoints, { Vector(-348.41909790039,-1619.8428955078,389.03125), Angle(12.9106092453,39.409847259521,0) } ) 
table.insert ( SpawnPoints, { Vector(-210.67851257324,-1597.1448974609,389.03125), Angle(12.28796005249,131.14163208008,0) } ) 
